### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by eddrc** [deeptools/pyGenomeTracks#101]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [x] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [x] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.

  - [x] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

  - [x] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

pyGenomeTracks --version
Illegal instruction: 4

python --version
Python 3.6.7

I am trying to install pygenometracks through conda and it seems I cannot. The McOS version I am using is: MacOS Sierra 10.12.6., the processor is 2 x 2.4 GHz Quad-Core Intel Xeon.

Thank you for your help

@lldelisle already took a look at it. We are stuck.

**Comment by bgruening** [comment]
The installation went fine, but it is not working? Or did you get an error during installation?

**Comment by bgruening** [comment]
```
(pygenometracks) bag@bag:~/projects/code/galaxytools/tools/salmon$ pyGenomeTracks --version
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
pyGenomeTracks 3.1
```

How have you installed pyGenomeTracks? Can you use `conda create` and give us the output?

**Comment by lldelisle** [comment]
The installation went fine but it is not working.
When he does:
`import pygenometracks` on python it does not give any error but if he tried `import pygenometracks.makeTracksFile` for example, it gives `Illegal instruction: 4`.

**Comment by joachimwolff** [comment]
Hi,

I just tested it on a Mac, and it works fine.

- How did you install it? Please post the command
- Which conda version do you use?

Best,

Joachim

**Comment by joachimwolff** [comment]
One more question: Can you set all dependencies back to the exact versions that are listed in our requirments.txt? I.e. no >=:
```
numpy =1.16
matplotlib =3.0
intervaltree =2.1.0
pybigwig =0.3.4
future =0.17.0
hicmatrix =9
pysam =0.14
pytest
gffutils =0.9
```

We have the idea that maybe this error comes from a dependency and not actually from pyGenomeTracks. As long as there is no fix, a usage of the old versions could help.

**Comment by lldelisle** [comment]
Hi,
You were right, it was a dependency issue:
using numpy=1.16 (and thus pybigwig=0.3.16) solved the issue.
Thank you very much,

By the way, we need to change the requirement.txt (pybigwig=0.3.4 -> numpy[version='1.10.*,1.12.*,>=1.9.3,<2.0a0'], so we should put pybigwig>=0.3.16).
