### ISSUE TITLE
Highlight specific gene in gene track?

### ISSUE THREAD

**Issue by dylan-plummer** [deeptools/pyGenomeTracks#104]
Hi, 

Love the package, it has been super simple to set up and I am using it to design an application that allows users to explore different datasets by searching for a gene.  I was wondering if it is currently possible to highlight a specific gene in the gene track by, for example, setting it to a different color?  The goal of this is to allow users to search for a gene which will be shown highlighted with the surrounding genes displayed as normal.

Thank you!

**Comment by bgruening** [comment]
@dylan-plummer you could display two gene tracks. One only with your gene and the other with all other but your gene. Then you can give these different colors.

Btw. do you know https://github.com/deeptools/HiCBrowser it uses pygenometracks to plot and browse, search data and display it.

**Comment by lldelisle** [comment]
@dylan-plummer, if you are using a bed file, you can also change the color field (9th column) (cf https://genome.ucsc.edu/FAQ/FAQformat.html#format1) and use in the config file `color = bed_rgb`. Alternatively, you can use the score color field (5th column) and use in the config file a colormap as color, for example `color = winter`.

**Comment by dylan-plummer** [comment]
@bgruening, @lldelisle  thank you for your suggestions.  I am displaying datasets that are specific to my own research and this application will pair those datasets with existing ones that pyGenomeTracks is able to plot.

 I have had luck in displaying two gene tracks to accomplish this, however the tracks automatically scale the axis limits to the data in the plots so the gene I am trying to highlight takes up the full track and doesn't correspond to the locations shown in the full gene track:
![Capture](https://user-images.githubusercontent.com/13262754/66413410-52e3ca00-e9c5-11e9-8671-5dae06ef7333.JPG)  

Is there a config parameter to set the axis range based on a genomic start and end locations?
