### ISSUE TITLE
Is it possible to disable binning and plot at basepair resolution ?

### ISSUE THREAD

**Issue by gouthamatla** [deeptools/pyGenomeTracks#106]
Hi,

I would like to know if its possible to disable binning and plot the signal at basepair resolution ?

Thanks,
Goutham A

**Comment by LeilyR** [comment]
Are you going to plot bigwig files? There is this option for bigwigs:

# The number of bins takes the region to be plotted and divides it into the number of bins specified
# Then, at each bin the bigwig mean value is computed and plotted.
# A lower number of bins produces a coarser tracks
number of bins = 500

**Comment by gouthamatla** [comment]
Thanks. I am plotting from bigwigs. So to disable binning, the number of bins should be set to the length of the region I'm plotting (?)

**Comment by lldelisle** [comment]
Hi,
With bigwig it will always bin whereas with bedgraph it will not. However, when you set the number of bin to the length of the region, you have something really close to no binning.
To show you, I took the bigwig available for the example (https://github.com/deeptools/pyGenomeTracks/blob/master/examples/bigwig.bw). I converted it to bedgraph with UCSC tool and I plot the bigwig without setting the number of bin, then the bigwig with the number of bin equal to the number of bases, and finally the bedgraph.
```INI
[bigwig file test]
file = bigwig.bw
# height of the track in cm (optional value)
height = 1
title = bigwig
min_value = 0
max_value = 5

[bigwig file test2]
file = bigwig.bw
# height of the track in cm (optional value)
height = 1
title = bigwig number of bins = 400000
min_value = 0
max_value = 5
number of bins = 400000

[bedgraph]
file=bigwig.bedgraph
height = 1
title = bedgraph
min_value = 0
max_value = 5
```

`pgt --tracks bigwig_bdg_track3.ini  --region X:2700000-3100000 -o test3.pdf --trackLabelFraction 0.2`
[test3.pdf](https://github.com/deeptools/pyGenomeTracks/files/3760817/test3.pdf)

**Comment by LeilyR** [comment]
@gouthamatla  indeed
