### ISSUE TITLE
How to show uncertainty, error bars, or multiple lines?

### ISSUE THREAD

**Issue by slowkow** [deeptools/pyGenomeTracks#11]
Hi Fidel,

Thanks for the excellent package! I want to use it with my own data, but I wonder if you can help me to show multiple replicates of a specific measurement.

You have a nice example in the README.md:

<img width="817" alt="deeptools_pygenometracks__python_module_to_plot_beautiful_and_highly_customizable_genome_browser_tracks" src="https://user-images.githubusercontent.com/209714/37412678-c5612ad6-277b-11e8-8501-a8e0f9a94bd2.png">

I'm looking at the second track with the blue line and the gray lines.

Could you please share the config.ini for this type of track?

In general, where can I find more information about existing configurations such as `[genes]`? For example, I'd like to know if I can use a GTF file for `[genes]`, or if that will have to be added as a custom track.

Before I try to make my own custom tracks, I was hoping that I might try to reuse one of the existing ones.

Thanks for any tips!

**Comment by vivekbhr** [comment]
Hi @slowkow . Maybe I can help.

One example of such file is [here](https://github.com/deeptools/HiCBrowser/blob/master/example_browser/tad_score.gz). It's referred as `[bedgraph matrix]` in the config. Basically, it's a bedgraph file (chr, start, end, score) with extra columns for scores from replicates.

For additional information on config files, the current [hicPlotTADs](http://hicexplorer.readthedocs.io/en/latest/content/tools/hicPlotTADs.html#hicplottads) documentation might be helpful. Additionally, config files with some explanation of fields can directly be generated from a list of files using `make_tracks_file`. Genes can be represented as bed6 or bed12 files at this moment.

**Comment by fidelram** [comment]
I added a new example to the README.md Maybe that helps.

**Comment by slowkow** [comment]
Hi Fidel, that's a great example. Could I ask you to please share the configuration?

I guess the gray lines are plotted with a configuration that looks something like this:

```ini
[bedgraph matrix]
# a bedgraph matrix file is like a bedgraph, except that per bin there
# are more than one value separated by tab: E.g.
# chrX       18279   40131   0.399113        0.364118        0.320857        0.274307
# chrX       40132   54262   0.479340        0.425471        0.366541        0.324736
# bedgraph matrices are produced by hicFindTADs
file = spectra_conductance.bm
title = conductance spectra
width = 1.5
orientation = inverted
min_value = 0.10
max_value = 0.70
# if type is set as lines, then the TAD score lines are drawn instead
# of the matrix
# set to lines if a heatmap representing the matrix
# is not wanted
type = lines
file_type = bedgraph_matrix
```

For the mean, are you creating an additional bedgraph file and then plotting it? What does the configuration look like for that?

**Comment by fidelram** [comment]
Yes, the configuration looks like that. When you use the `bedgraph_matrix` file_type, the mean is computed based on the data. No extra file is needed.

**Comment by werhmk** [comment]
hi,Fidel,
how to handle with a GFF3 file, should it be convert to BED file? 
thanks.

**Comment by bgruening** [comment]
Hi @werhmk!

Please try the latest release - it has gtf support: https://github.com/deeptools/pyGenomeTracks/releases/tag/3.1  That should hopefully work.
