### ISSUE TITLE
Other summary methods for bigwig

### ISSUE THREAD

**Issue by Benfeitas** [deeptools/pyGenomeTracks#112]
Related [with a previous issue](https://github.com/deeptools/pyGenomeTracks/issues/15), I'm wondering if it would be possible to add the other summary methods found in WashU, including "sum" and "count"?

**Comment by lldelisle** [comment]
Hi,
- `sum` is already available as pygenometracks depends on pyBigWig and since version 0.3.11 you can use mean/average/stdev/dev/max/min/cov/coverage:
https://github.com/deeptools/pyBigWig/blob/86b096511c548f481348ad9961e65c653a202fd8/libBigWig/bigWig.h#L53-L64

- What do you mean by count?

**Comment by Benfeitas** [comment]
That's perfect, thanks for the quick reply. I missed those in the docs. I only mentioned counts since it's also displayed in WashU, but for my purposes these summary methods are more than enough!
