### ISSUE TITLE
on/off yes/no TRUE/FALSE in parameters

### ISSUE THREAD

**Issue by lldelisle** [deeptools/pyGenomeTracks#117]
For me it is a bit confusing that some options are on/off, some others are yes/no and finally, some others are TRUE/FALSE.
For example:
https://github.com/deeptools/pyGenomeTracks/blob/1352c2a16ab4ada31bcf8fa06d34df3a83422dad/pygenometracks/tracks/BedTrack.py#L144
https://github.com/deeptools/pyGenomeTracks/blob/1352c2a16ab4ada31bcf8fa06d34df3a83422dad/pygenometracks/tracks/BedTrack.py#L270
This can be heavy:
https://github.com/deeptools/pyGenomeTracks/blob/1352c2a16ab4ada31bcf8fa06d34df3a83422dad/pygenometracks/tracks/NarrowPeakTrack.py#L153
or
https://github.com/deeptools/pyGenomeTracks/blob/1352c2a16ab4ada31bcf8fa06d34df3a83422dad/pygenometracks/tracks/HiCMatrixTrack.py#L75

What I propose is to use Boolean in self.properties, as in:
https://github.com/deeptools/pyGenomeTracks/pull/102/commits/3d87e36ffbca90fa12906f80c39e2199d3c81104
thanks to:
`parser.getboolean`
see in tracksClass.py:
```
                elif name in ['labels', 'show data range',
                              'plot horizontal lines', 'use middle',
                              'rasterize', 'global max row',
                              'show_masked_bins', 'show labels',
                              'use summit', 'skip']:
                    try:
                        track_options[name] = parser.getboolean(section_name,
                                                                name)
                    except ValueError:
                        log.error("In section {}, {} was set to {}"
                                  " whereas we should have a boolean value."
                                  "Please, use "
                                  "{}".format(section_name, name, value,
                                              str([k for k in parser.BOOLEAN_STATES])))
                        exit()
```

Then, we can still check that all our examples fit the same standard but this will make the old ini files still work...

**Comment by LeilyR** [comment]
#121
