### ISSUE TITLE
--vlines is not used

### ISSUE THREAD

**Issue by lldelisle** [deeptools/pyGenomeTracks#131]
Hi,
In the parser there is a `--vlines` option but it is not used afterward:
https://github.com/deeptools/pyGenomeTracks/blob/1352c2a16ab4ada31bcf8fa06d34df3a83422dad/pygenometracks/plotTracks.py#L210-L215
for example:
```
pgt --tracks ./pygenometracks/tests/test_data/bigwig.ini --region X:2700000-3100000 --trackLabelFraction 0.2 --dpi 130 -o ./pygenometracks/tests/test_data/master_bigwig.png --vlines 3000000
pgt --tracks ./pygenometracks/tests/test_data/bigwig.ini --region X:2700000-3100000 --trackLabelFraction 0.2 --dpi 130 -o ./pygenometracks/tests/test_data/master_bigwig.png
```
give the same.
The reason why is that it is not given to :
https://github.com/deeptools/pyGenomeTracks/blob/1352c2a16ab4ada31bcf8fa06d34df3a83422dad/pygenometracks/plotTracks.py#L275-L276

Should I fix it or remove this option from the parser?

**Comment by LeilyR** [comment]
#137 fixed this
