### ISSUE TITLE
overlay a horizontal line

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/pyGenomeTracks#139]
is it possible to add a horizontal line at any given Y value right into the track code ? or do I need to create a bedgraph containing the Y value at all positions?

**Comment by lldelisle** [comment]
For the moment, I do not think it is possible. But indeed you can use a bedgraph with one interval per chromosome with the Y value.

**Comment by rikrdo89** [comment]
Thanks a lot for your prompt response! I'll try that!
