### ISSUE TITLE
Min and Max summary methods for bigwig tracks

### ISSUE THREAD

**Issue by prmunn** [deeptools/pyGenomeTracks#15]
Would it be possible to add Min and Max summary methods to the display of bigwig tracks, similar to the way that the WashU Epigenome browser works (currently, I assume you're using 'average' as the summary method).

Many thanks

**Comment by fidelram** [comment]
Indeed, the default is the mean. I addressed your comment in the PR #16 Now, you can set `summary method = max` The options are min, max and mean and the default is mean.
