### ISSUE TITLE
hicPlotTADs did not show the scale

### ISSUE THREAD

**Issue by benxiahu** [deeptools/pyGenomeTracks#154]
hello,
   I used hicPlotTADs to plot TADs. However, the figure did not show the scale.
here is my code:
[x-axis]
where = top

[hic]
file = merged_Corrected_40kb.h5
title = XY
depth = 160000
transform = log1p
file_type = hic_matrix

[tads]
file = TADs_40kb_domains.bed
file_type = domains
border color = black
color = none
display = triangles
overlay previous = share-y

![image](https://user-images.githubusercontent.com/12387462/70476470-bc0abb00-1aa4-11ea-9050-2a99020fa7e5.png)

**Comment by LeilyR** [comment]
@benxiahu please follow all the step i have mentioned in my previous comment. You need a fresh env. If you follow the above steps your matplotlib will be updated to 3.1.2.

**Comment by lldelisle** [comment]
I think you can also just upgrade pygenometracks. You might have a version <3.1 and we solved this issue in 3.1...

**Comment by lldelisle** [comment]
It looks like you managed to fix the issue. If it is not the case, feel free to reopen it.
