### ISSUE TITLE
did not show full triangle

### ISSUE THREAD

**Issue by benxiahu** [deeptools/pyGenomeTracks#155]
when I used pyGenomeTracks to plot TADs, but the triangle of TADs did not show.
![image](https://user-images.githubusercontent.com/12387462/70642767-d0b69280-1c0d-11ea-87ab-1e7bbae56bc0.png)

**Comment by lldelisle** [comment]
Hi,
If you want to see the full triangle, you need to increase the depth parameter:
You put `depth = 200000`, this means that you want to see only interaction closer than 200kb...
If you put `depth = 1200000` you will see the interactions between the start and the end of your region, thus you would see every thing.
Also, if you want to have the height automatically adjusted to the depth you can remove the line height = 5.

**Comment by lldelisle** [comment]
I think I can close the issue but if it is not solved, please, feel free to reopen it.
