### ISSUE TITLE
y-axis font size

### ISSUE THREAD

**Issue by adomingues** [deeptools/pyGenomeTracks#167]
- [X] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [X] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
pyGenomeTracks 3.2
Python 3.6.9
Pip install.

  - [x] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

```bash
pyGenomeTracks --tracks tracks_strand.ini --fontSize 14 --region chr20:10480250-13173750 --outFileName figure/nice_image.pdf
```

  - [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

Not an issue as such,  but I couldn't find how to set the font size of the y axis. I used `--fontSize 14` but, as documented, that affects only the track labels. Is there a way to also increase the font size of the y-axis?

**Comment by adomingues** [comment]
Please ignore.  `--fontSize` also changes the font size of the y-axis. I missed it because the increase in my test was not large enough.

**Comment by lldelisle** [comment]
This is so nice when people manage to solve issues by themselves...
If you have other questions, do not hesitate to submit another issue.
