### ISSUE TITLE
Jupyter notebook

### ISSUE THREAD

**Issue by iamjli** [deeptools/pyGenomeTracks#17]
Hi there, 

Is there an example of how this could be used in a notebook? Or is this package not meant to be used that way? 

Thanks!

**Comment by bgruening** [comment]
It can be used, but is not as easy as I could be. We will work on this and add an example notebook.

**Comment by fidelram** [comment]
Check this issue: [Using in python scripts](https://github.com/deeptools/pyGenomeTracks/issues/8)

copying from there:

```python
import matplotlib.pyplot as plt
from pyGenomeTracks import BigWigTrack

# make a properties dict using as keys the values from the 
# documentation. Here an example of a bigwig file:
properties_dict = {'file': <path bigwig file>, 'height': 3, 'title'='bigwig', 'color'='red}

# initialize a bigwig track with the properties_dict. Any of the available tracks can be
# initialized in the same way
bw = BigWigTrack(properties_dict)

# to plot the region two axes are needed, one for the plot itself and the other for the legend.
figure, (track_ax, label_ax) = plt.subplots(1, 2)

# the plot method of all track classes expects 5 values, the track_ax, 
# the label_ax, and the genomic region to plot (chrom, start, end).
bw.plot(track_ax, label_ax, chrom, start, end)
```

**Comment by iamjli** [comment]
Thanks!

**Comment by mooratov** [comment]
Hello,  I'm trying to do the same thing but no luck. I've successfully installed the software via pip, and can run the executables generated by the installation, but cannot import the library into jupyter notebook or script

```
which pyGenomeTracks
/Library/Frameworks/Python.framework/Versions/3.6/bin/pyGenomeTracks
```

in the python interpreter:
```
>>> import pyGenomeTracks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyGenomeTracks'
```

if i use the lowercase "pygenometracks", the import is successful, but this does not seem to be the library i need.

**Comment by mooratov** [comment]
ok i figured out this basic hurdle. It seems in the latest version you instead need to do something like 
```
from pygenometracks import tracks
properties_dict = {'file': 'whatever.bed', 'height': 3, 'title':'dong', 'color':'red'}
bed = tracks.BedTrack(properties_dict)
```

but i'm still having a hard time getting this to work how i want it to. I will ask in the other issue as well
