### ISSUE TITLE
Too less space for file names

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/pyGenomeTracks#178]
Hi,

using the current version I have recognized the space reserved for names of the samples is quite limited. Would be nice if we can have here a bit more space to the right if the names are quite long.

![Galaxy36--pyGenomeTracks_on_-data_29-_data_25-_and_data_22-__Plot-](https://user-images.githubusercontent.com/13435136/73186958-e7af3680-4120-11ea-97d1-f20aa695d4dd.png)
![download](https://user-images.githubusercontent.com/13435136/73186970-ed0c8100-4120-11ea-81d9-a60ed131807c.png)

Note to myself @joachimwolff: The default value for TAD-score track in the Galaxy wrappers for the option 'lines' should be set to yes. Otherwise we get this nice matrix instead of a curve.

Best,

Joachim

**Comment by lldelisle** [comment]
In the command line version we can use:
`--trackLabelFraction`
I/you should probably enable it in Galaxy.

**Comment by lldelisle** [comment]
https://github.com/galaxyproject/tools-iuc/pull/2945 provide the `--trackLabelFraction`.
Do you want me to change the default of bedgraph matrix?
