### ISSUE TITLE
Genes visualisation styles

### ISSUE THREAD

**Issue by Hoxd13** [deeptools/pyGenomeTracks#180]
Hello there,

I'm a new user of your promising tool and I have a couple of suggestions for you.
Would it be possible to implement these options (evolving from and around the UCSC mode, I guess) to:

a) draw an arrow over each gene's TSS.
b) hide introns and draw lanes connecting a gene's exons together.
c) color differently genes depending on their Watson/Crick transcriptional direction.
d) draw a scale on the figure to help representing some sort of genetic distance, proportioned to the genetic interval provided by the user (something like 1/10 of the total interval)

That would be super useful to generate illustration centered on a precise (dense) locus - see screenshot below - it should illustrate these four points. I might of course have missed some of these parameters from your readme.

cheers
Fabrice

<img width="1138" alt="illustration_pyGT" src="https://user-images.githubusercontent.com/52430774/73204197-655c4d80-40f3-11ea-86d0-8200f740a416.png">

**Comment by lldelisle** [comment]
Hi Fabrice,
For a) b), would you keep the labels below? or they can be on the right, as for the other styles?
For c), I think you can use the rgb field:
`awk -F "\t" -v OFS="\t" -v colorPos="0,0,255" -v colorNeg="255,0,0" '$6 == "+"{$9 = colorPos}$6 == "-"{$9 = colorNeg}{print}' input.bed > output_strand_matched_color.bed`
Then use `color = bed_rgb`.
For d) This is a good idea.

**Comment by Hoxd13** [comment]
Hi Lucille,
For a) and b) - make it as simple as possible for you, from a coding point of view. 
I'm fine with any label position, it's anyway easy to edit and move genes names manually from the pdf output.
c) thanks for the piece of code!
d) I think it might be useful to a lot of users, when drawing large genetic intervals from C datasets.

**Comment by lldelisle** [comment]
a) and b) are done in PR #184:
![master_bed_genes_rgb](https://user-images.githubusercontent.com/30404086/73440131-08f66980-4351-11ea-8dd2-63a8ab5eafe0.png)
I think we are pretty close.
For d) this will be my next PR...

**Comment by lldelisle** [comment]
Et voilà #185 for the scale bar.

**Comment by Hoxd13** [comment]
Super merci Lucille! Ca fait plaisir de retrouver le chromosome 2 et le cluster.
(Also pretty cool how you can color differently UTRs versus CDS!)
cheers
F

**Comment by lldelisle** [comment]
Hey,
It is now available in version 3.3.
