### ISSUE TITLE
Crashing if empty input for TAD boundaries file

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/pyGenomeTracks#181]
Hi,

using the current version and plotting a Hi-C matrix and Tad boundaries. If now the TAD boundaries are empty, pyGenomeTracks is crashing without any useful error message.

I see two options: a) do not plot any Tad boundaries because file is empty but not let the whole thing crash or b) check all inputs if they contain data and if not return error message which input is actually empty.

Best,

Joachim

**Comment by lldelisle** [comment]
Could you give a config file + input file example?

**Comment by lldelisle** [comment]
Solved in version 3.3
