### ISSUE TITLE
Unable to view nearby arcs when an interaction is far away

### ISSUE THREAD

**Issue by Benfeitas** [deeptools/pyGenomeTracks#187]
I have generated a few arcs successfully, but the problem is that when one of the interactions lies far away (>1mb ?), the nearby interactions basically show as flat lines and only the far away interaction is discernible. Is there. away to allow for all interactions to be better shown?

I can see in [here](https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tracks/LinksTrack.py#L164) that this was intended, but I'm looking for a way to bypass it and allow each arc to have the same height.

**Comment by lldelisle** [comment]
Hi,
I think we could indeed avoid flat lines. 
Please, could you provide an example or give more details: It happens when you have both close and far loops? When you try to see both?
Thanks for reporting this issue, we are happy to improve our tool.

**Comment by Benfeitas** [comment]
Hi! This happens when I try to view both the close and far loops. For instance:

![Screenshot 2020-02-10 at 12 22 59](https://user-images.githubusercontent.com/25486866/74145970-5d76d000-4c00-11ea-9f68-c81a9b2d714f.png)

This file contains 4 loops:

```
chr11	44400062	44400063	chr11	44463769	44463770	1.0413926851582251
chr11	44400062	44400063	chr11	44491868	44491869	0.9542425094393249
chr11	44400062	44400063	chr11	44570423	44570424	0.8450980400142568
chr11	100029868	100029869	chr11	44754820	44754821	0.7781512503836436     
```

Dropping the last line, which contains the distant interaction, solves the problem:

![Screenshot 2020-02-10 at 12 28 33](https://user-images.githubusercontent.com/25486866/74146215-eee64200-4c00-11ea-86d8-e147483ee757.png)

I understand this is a very particular case, since you probably want to view the full loop even if it is distant. But in this case, I'd like to be able to see that there are nearby and distant loops ending in this particular locus

**Comment by lldelisle** [comment]
Thanks,
I will try to propose you different options and you will tell me which one fit best your expectations.

**Comment by lldelisle** [comment]
Hi,
I propose to add 2 parameters:
```
# To be able to see small arcs when big arcs exists, you can set
# the upper y limit.
# The unit is bp. This corresponds to the longest arc you will see.
#ylim = 100000
# If you want to compact the arcs (when you have both long and short arcs)
#compact_arcs = true
```
Here are examples:
![master_short_long_arcs](https://user-images.githubusercontent.com/30404086/74237951-f70fb180-4cd4-11ea-90fe-bc197bf48951.png)
Could you tell me what do you think?
Would this solve your issue?

**Comment by Benfeitas** [comment]
Hi @lldelisle , thanks, this is quite good. To see if I understood, by using `ylim`, you are excluding from plotting any arcs with a distance larger than that specified. Correct?

I'm wondering if it would make sense to have the `compact_arcs = true` enforcing that all arcs have the same height? I.e., the vertices in each triangle would be at the same yy coordinate.

**Comment by lldelisle** [comment]
Hi,
`ylim` just do a zoom in on the y axis, it does not remove the arcs, just crop the image.
I could do a `compact_arcs_level` that could be 0 = normal, 1 = like in the figure, 2 = all at the same height.

**Comment by Benfeitas** [comment]
I see!   Yes, having `compact_arcs_level` like that would be really perfect! Thanks a lot for all your help already

**Comment by lldelisle** [comment]
![master_short_long_arcs](https://user-images.githubusercontent.com/30404086/74243172-8b7f1180-4cdf-11ea-9b5c-6da33acfbb84.png)

**Comment by Benfeitas** [comment]
Really like it when it shows `compact_arcs_level = 2`. My motivation for asking this was that it would be possible for you to not notice some of the interactions if they were very proximal. Thanks again

**Comment by lldelisle** [comment]
OK I open the PR

**Comment by Benfeitas** [comment]
Hi again! I pulled from `devel` branch and have been testing a few things. When I specify `links_type = arcs`, I see `these parameters are unused:['compact_arcs_level']`, which makes sense. I then see the arcs as they were before.

When I specify `links_type = loops`, I don't get any issue with the log, aside from `DEBUG:pygenometracks.tracks.GenomeTrack:50 were links plotted`. The problem is that nothing shows in the generated tracks. 

Here's what I'm specifying:

```
[arcs test]
file = /my/path/test.arcs
color = brg
links_type=loops
compact_arcs_level=2
title = test
height = 3
```

just swapping `links_type=arcs` solves the issue, but doesn't apply the fix you made above

**Comment by lldelisle** [comment]
How did you pulled the `devel` branch?

**Comment by Benfeitas** [comment]
`!pip3 install --upgrade --force-reinstall git+https://github.com/deeptools/pyGenomeTracks.git@develop`

**Comment by lldelisle** [comment]
My PR is not merged yet...
You need to install https://github.com/lldelisle/pyGenomeTracks.git@fixLinks

**Comment by Benfeitas** [comment]
Sorry, but it still doesn't solve the problem. The only difference is changing `links_type=arcs` to `links_type=loops` and it stops showing any interactions at all

**Comment by lldelisle** [comment]
So when you use loops you don't see them right?
Did you increase the line_width?

**Comment by lldelisle** [comment]
The loops will make a square between the starts and the ends of the links. If the width of the loop is 1, then, they are very difficult to see...

**Comment by Benfeitas** [comment]
That makes sense, I hadn't specified any `line_width` at all, but adding `line_width = 10` solves the issue. 
I'll close this. Thanks for all your help, this is great!
