### ISSUE TITLE
tests/test_data not available - trying to determine data format for chromatin track color designation

### ISSUE THREAD

**Issue by sonnynguyen** [deeptools/pyGenomeTracks#211]
Hi, I noticed that the test data is no longer available.  I was hoping to do something similar to the "chromatinStates_kc.bed.gz" and be able to designate specific colors to the specific tracks.  Is this possible?

**Comment by sonnynguyen** [comment]
Nevermind, I was able to find it under pygenometracks/tests/test_data/.  Some links may have to be updated to point to this new directory (For example, the "test_data/" link at the top of this page: https://pygenometracks.readthedocs.io/en/latest/content/examples.html#

**Comment by lldelisle** [comment]
Indeed thanks for the bug report.

**Comment by lldelisle** [comment]
To designate colors to specific bed intervals you can use either the score field (5th) and use a colormap as color as in:
```
[test bed6]
file = dm3_genes.bed6.gz
height = 7
title = bed6 border_color = black; gene_rows=10; fontsize=7; color=Reds
        (when a color map is used for the color (e.g. coolwarm, Reds) the bed
        score column mapped to a color)
fontsize = 7
file_type = bed
color = Reds
border_color = black
gene_rows = 10
```
Or you can use the 9th field as in the chromatinStates with `color=bed_rgb` in the configuration file.
The way to use the 9th field is described here: https://genome.ucsc.edu/FAQ/FAQformat.html#format1

**Comment by lldelisle** [comment]
The url is updated, thank you.
