### ISSUE TITLE
request: simple GWAS track

### ISSUE THREAD

**Issue by ycooper27** [deeptools/pyGenomeTracks#212]
Was hoping for some help designing a simple track to plot GWAS data. Would take a file with chr, pos, and -log(p-value), and would simply plot points at the appropriate coordinates (chr and pos for x-axis; -log(p-value) for y-axis).

Thanks!

**Comment by lldelisle** [comment]
Hi,
I would recommand to preprocess your input file to transform it to bedgraph with the following command:
```
cat input_file_GWAS.txt | awk -v OFS='\t' '{print $0, $1, $1+1, $2}' > input_file_GWAS_converted.bedgraph
```
Then you can create a ini file, for example:
```ini
[x-axis]
where = top
[GWAS]
title = GWAS
file = input_file_GWAS_converted.bedgraph
file_type = bedgraph
type = points:5
color = black
use_middle = true
height = 5
min_value = 0
max_value = 20
```
For more details you can use:
```
make_tracks_file -f input_file_GWAS_converted.bedgraph -o tracks.ini
```
However, I need to tell you that depending on the size of the input file, it can be very long to plot as pygenometracks will load (in the current version) the whole file before plotting so it can be interesting to convert the bedgraph to bigwig with the UCSC tool (you can download from here: http://hgdownload.cse.ucsc.edu/admin/exe/).

Tell me if it solves your issue.

**Comment by ycooper27** [comment]
this solution worked nicely, thank you for your help!
