### ISSUE TITLE
gene name can not be showed

### ISSUE THREAD

**Issue by benxiahu** [deeptools/pyGenomeTracks#213]
Hi,
 I want to plot a region of  1Mb with pyGenomeTracks. However, the gene names can not be showed.
I am running pyGenomeTracks 3.2. I set the fontsize to 80. Do you know how to solve this issue?
Best,
Thanks

![image](https://user-images.githubusercontent.com/12387462/80433989-87b66080-88c6-11ea-99c7-e091dfb1e1ce.png)
 
![image](https://user-images.githubusercontent.com/12387462/80434070-c3e9c100-88c6-11ea-848b-5ac39b23a714.png)

**Comment by lldelisle** [comment]
Hi,
Indeed our documentation is still not complete.
If you use `make_tracks_file --trackFiles input.bed -o template.ini` you will see all the options available for the bed files. There is one which is `max_labels`:
```
# by default the labels are not printed if you have more than 60 features.
# to change it, just increase the value:
#max_labels = 60
```
So if you add `max_labels = 200` in your configuration file you should see the names of the genes.

Tell me if it solves your issue.
