### ISSUE TITLE
Display y-axis ticks and grid lines in bigwig track graph

### ISSUE THREAD

**Issue by guerler** [deeptools/pyGenomeTracks#214]
It would be nice to enable y-axis ticks and automated horizontal grid lines in the bigwig track graph. Currently only the minimum and maximum values are shown by default which makes it difficult to read/guess the actual values.

![y-axis-not-informative](https://user-images.githubusercontent.com/2105447/80927461-1108df80-8d6c-11ea-9050-5ffa7a2ec28b.png)

**Comment by lldelisle** [comment]
Hi,
Good improvement idea. We put it in the TODO list.

**Comment by lldelisle** [comment]
Is it what you were looking for?
![master_grid](https://user-images.githubusercontent.com/30404086/82354029-8af1c780-9a00-11ea-8bba-827799e52476.png)

**Comment by dannon** [comment]
@lldelisle That looks great, it would help a lot!  Is the line spacing configurable?

**Comment by lldelisle** [comment]
No...
For the moment I only added major ticks

**Comment by guerler** [comment]
Thanks @lldelisle, that is a huge improvement for the readability.

**Comment by lldelisle** [comment]
For the moment, it is available here: https://github.com/lldelisle/pyGenomeTracks/tree/grid
But I am still working on it especially on the y axis when the log transformation is used.
It should be ready by tomorrow.

**Comment by dannon** [comment]
@lldelisle Fantastic, thanks!

**Comment by lldelisle** [comment]
Hi,
grid is now available in version 3.5.
