### ISSUE TITLE
hicmatrix>=12 cannot be found

### ISSUE THREAD

**Issue by Zepeng-Mu** [deeptools/pyGenomeTracks#228]
While running `pip install pyGenomeTracks`, I got the following message:
``` 
Defaulting to user installation because normal site-packages is not writeable
Collecting pyGenomeTracks
  Using cached pyGenomeTracks-3.3-py2.py3-none-any.whl (80 kB)
Collecting future>=0.17.0
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting pyBigWig>=0.3.16
  Using cached pyBigWig-0.3.17.tar.gz (64 kB)
Collecting matplotlib==3.1.1
  Using cached matplotlib-3.1.1-cp37-cp37m-manylinux1_x86_64.whl (13.1 MB)
ERROR: Could not find a version that satisfies the requirement hicmatrix>=12 (from pyGenomeTracks) (from versions: 5, 7, 10, 11)
ERROR: No matching distribution found for hicmatrix>=12 (from pyGenomeTracks)
```
I think this is because hicmatrix version is not correct, but I cannot figure out how to install the correct version.
Thanks

**Comment by lldelisle** [comment]
Hi,
Thanks for reporting this issue, we are really sorry for the inconvenience, we forgot that hicmatrix was not maintained on pip, we will try to fix it... 
Meantime, the easiest way would be to install it through conda. You can download miniconda here: https://docs.conda.io/en/latest/miniconda.html depending on the python installed on your machine you need to install miniconda2 or miniconda3. Then you can install pyGenomeTracks with:
```
$ conda install -c bioconda -c conda-forge pygenometracks
```
Let me know if you still have issues.

**Comment by Zepeng-Mu** [comment]
Hi, thank you for the quick response!
I am going to try installing from conda. It's just that conda is really slow.

**Comment by joachimwolff** [comment]
I just added version 12 of hicmatrix to pypi. Please let me know if there are any issues.
