### ISSUE TITLE
plot bedgraph with minus data

### ISSUE THREAD

**Issue by hugch2010** [deeptools/pyGenomeTracks#235]
Hi, 
I want to draw bedgraph track with plus and minus data in two colors, is there any way to achieve this?

Best,
Gongcheng

**Comment by lldelisle** [comment]
Hi,
Sure, you can use `color` and `negative_color`.
The possible parameters for bedgraph are available here: https://pygenometracks.readthedocs.io/en/latest/content/tracks/bedgraph.html
I just realize that this is not part of the output of make_tracks_file, thanks for reporting this issue.
