### ISSUE TITLE
Vertical axis line for data range

### ISSUE THREAD

**Issue by jma1991** [deeptools/pyGenomeTracks#24]
What setting do I specify to set the Y-axis of a bigWig track to a vertical line? Right now the data range is drawn like "[0 - 10]" but I would like the vertical axis line as demonstrated in the tracks on the homepage.

I'm using version 2.0 from bioconda with Python 3

**Comment by vivekbhr** [comment]
We use the vertical lines to mark intervals (from bed files), the way you specify this is using `type = vlines` in the config file. Do you rather want the vertical lines to present genomic scores?

**Comment by jma1991** [comment]
Yes on the left hand side of the bigWig track where it shows the range of the coverage / genomic score. Currently I can only get it to show the range as “[0 - 3]” but in the snapshot examples the range is show as a vertical y-axis

**Comment by vivekbhr** [comment]
Ok now I got it. Yes the line on the Y axis can be drawn when you specify "show data range = yes" in the `config.ini` for the bigwig track

**Comment by vivekbhr** [comment]
Could you try again using the latest master branch from this repo? using `pip install  git+https://github.com/maxplanck-ie/pyGenomeTracks.git`

**Comment by jma1991** [comment]
Unfortunately I haven’t been able to do that, I’m working on a shared server without root access so I’ve been using bioconda for software installation.

If I clone the repo and run:

python setup.py install

It builds correctly but Python can’t find the module files because conda doesn’t look at the PYTHONPATH variable. If I try pip install, then the installation hangs indefinitely.

**Comment by vivekbhr** [comment]
Sorry, I meant to use the pip provided by your conda installation (after removing the previous install of pyGenomeTracks)

**Comment by fidelram** [comment]
The y-axis line was added recently. Thus you need the latest version of
pyGenomeTracks. I should make a new pip release.

**Comment by vivekbhr** [comment]
@jma1991 I have added an environment.yaml file that should compile from the master branch (using pip within your conda). You can try `conda env create -f environment.yaml` followed by `source activate pygenometracks` to see whether you get new changes now.

**Comment by malbahrani** [comment]
I have the same issue as @jma1991, the Y-axis line is not showing in the plot.

I have installed `pyGenomeTracks` using `conda install -c bioconda pygenometracks` because it is easier when you're using a shared server with limited administrative access.  I am wondering, if I re-install the package with anaconda now, would I get the latest version of `pyGenomeTracks` with Y-axis issue fixed?

Thanks,

**Comment by vivekbhr** [comment]
We haven't yet updated the bioconda release yet, but the above solution would also work for you if you want to update your pyGenomeTracks to the latest master branch.

**Comment by malbahrani** [comment]
Not sure why, but when I type `conda env create -f environment.yaml`, I get this error message:
`SpecNotFound: Can't process without a name` ?

**Comment by vivekbhr** [comment]
Hmm. It should get the name form the yaml file. Try using absolute path to the environment.yml file.
