### ISSUE TITLE
Takes very long time to plot GTF files

### ISSUE THREAD

**Issue by Zepeng-Mu** [deeptools/pyGenomeTracks#241]
Hi,
I noticed that it takes about 8 hours for pyGenomeTracks to plot GTF files. Right now I am using full GFT files download from GENCODE. I am wondering whether there is a way to speed up, like filtering my GTF file to only include exons?
Thanks!

pyGenomeTracks 3.3
Python 3.7.0

**Comment by lldelisle** [comment]
Hi,
We are using gffutils and indeed if you keep only exons you should speed up by 5X.
However, if you want to use this gtf multiple times it may be interesting to convert it first to bed using for example this script [fromgtfTobed12.py](https://github.com/lldelisle/tools-lldelisle/blob/master/tools/fromgtfTobed12/fromgtfTobed12.py) which may be soon part of pygenometracks (use `python fromgtfTobed12.py -h` to see the usage).
If you are only interested in a specific region you can also subset your gtf keeping only a small region.

**Comment by Zepeng-Mu** [comment]
Thanks, right now I am using UCSC genome browser tools to convert GTF to BED12 format and it is super fast now. I also saw some tools using tabix-ed GTF with pysam to extract entries in a given region which seems to be fast.

**Comment by lldelisle** [comment]
Hi,
Cool that it solved your issue. I developed the python script because the name of the regions when we are using the UCSC genome browser tools is the transcript id and I prefer to have the transcript name or the gene name and I like to be able to merge all transcripts in one entry.
Thanks for the suggestion of tabix-ed GTF I did not know it...

**Comment by alexlenail** [comment]
The script `fromgtfTobed12.py` used with default settings on GENCODE's reference genome annotation gtf does not work. 

@Zepeng-Mu how did you convert your GTF to bed12?

**Comment by lldelisle** [comment]
Did you get an error?

**Comment by alexlenail** [comment]
```
AssertionError: File type detected is bed12 but line 203: chr16	85800	138512	NPRL3-201	0	-	86707	138267	0	12	1070,193,190,130,107,157,138,82,154,130,70,3630,2897,3912,6795,7418,12344,14571,24724,26821,33325,44721,52349
 does not have 12 fields.
```

This solved it for me: https://github.com/deeptools/pyGenomeTracks/issues/72#issuecomment-492258181

**Comment by lldelisle** [comment]
The issue with the tool from UCSC is that you don't get the gene name but the gene ID... If it is fine for you.
I am trying to reproduce the error. Which gencode gtf did you used?

**Comment by alexlenail** [comment]
V29. It's not a big deal. The python script also took a couple hours, whereas the UCSC utilities take a few seconds.

**Comment by lldelisle** [comment]
Now I remember. It is quicker if you only keep the lines for exons:
```
zcat gencode.v38.annotation.gtf.gz | awk '$3=="exon"{print}' > gencode.v38.annotation.exon.only.gtf
python fromgtfTobed12.py --output gencode2.bed gencode.v38.annotation.exon.only.gtf
```

**Comment by Zepeng-Mu** [comment]
@alexlenail I used two options:`--mergeTranscripts --mergeTranscriptsAndOverlappingExons` and there has been no error message for me and also very fast.
