### ISSUE TITLE
gene label not shown when gene number to large

### ISSUE THREAD

**Issue by silvewheat** [deeptools/pyGenomeTracks#26]
I have two gene file, one file contains 59 genes, anther contains 89 genes. When I draw tracks, the first genes set can show gene label, the other can't. And, I have set the "labels = on" in both track.
It seems caused by the gene number.
I also try to plot with a single gene file contain more than 100 genes, the label can't shown either.
![image](https://user-images.githubusercontent.com/19344997/40636881-425245d6-6334-11e8-9f78-fdbd5b64f1b8.png)

**Comment by vivekbhr** [comment]
The number of genes should not affect the plotting of gene names. Can you paste the `head` of both the files?

**Comment by silvewheat** [comment]
These two files are all in bed12 format that I used [ea-utils/gtf2bed](https://github.com/ExpressionAnalysis/ea-utils/blob/master/clipper/gtf2bed) transform from gtf file.
The first file (59 genes, label showed):
![image](https://user-images.githubusercontent.com/19344997/40647241-f97f20c0-635d-11e8-8abe-1b979b8f89ab.png)
The second file (89 genes, label unshowed):
![image](https://user-images.githubusercontent.com/19344997/40647435-6f33e634-635e-11e8-9237-2fac3859fcc7.png)

**Comment by fidelram** [comment]
I think that there is a limit of the number of genes with label that can be
seen. The threshold, if I remember correctly is 50. To view the labels
simple zoom in a bit.

**Comment by silvewheat** [comment]
I tried it, but it seems really no label.
And I also change the font size in .ini file, also didn't work.

**Comment by vivekbhr** [comment]
@silvewheat you might have to share the files with us to reproduce this issue. Do you mind attaching the files here?

**Comment by silvewheat** [comment]
Hello,
   I hvae upload my .ini, .bed ,and the result .bed file in the package.
  My command line is:
    pyGenomeTracks --tracks tracks.ini --region chr1:100732629-102527660 --outFileName genes.pdf
[debug.zip](https://github.com/deeptools/pyGenomeTracks/files/2086615/debug.zip)

Thanks!

**Comment by shenscore** [comment]
Hi, I met the same problem.
Have you found any resolutions ?

Thanks!

**Comment by silvewheat** [comment]
I reduced the number of genes.
╮(╯﹏╰）╭

**Comment by LeilyR** [comment]
A certain space has been defined for each label for the purpose or readability. This has been done based on an example from `https://scipy-cookbook.readthedocs.io/items/Matplotlib_LaTeX_Examples.html` , so I assume in your case there was not enough space for the labels. My suggestion would be breaking your region into smaller sub-regions if possible, in case you want to keep all the genes in your bed file.

**Comment by fidelram** [comment]
By default, to avoid overlapping gene names, labelling is turned off. I
think that the threshold is 50. Simply zoom in on a particular region or
prepare a bed file with less genes if you want to have a large area and
also show some genes.

**Comment by bgruening** [comment]
I think this one can be closed. Thanks to @lldelisle there is now also an option to include the gene count.
