### ISSUE TITLE
TAD and HiC matrix did not overlay

### ISSUE THREAD

**Issue by YichaoOU** [deeptools/pyGenomeTracks#267]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [X] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [X ] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.

```
(pygenometracks) [yli11@nodecn252 ~]$ python --version
Python 3.6.9 :: Anaconda, Inc.
(pygenometracks) [yli11@nodecn252 ~]$ pyGenomeTracks --version
pyGenomeTracks 3.1.2
```

  - [X ] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

```
[hic matrix]
file = hicexplorer_20kb.h5
title = Hi-C data
depth = 300000
height = 8
transform = log1p
file_type = hic_matrix

[tads]
file = tad_domains.bed
display = triangles
border_color = black
title = tad
file_type = domains
color = none
height = 8
line_width =  5
overlay_previous = share-y

```

  - [ X] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

I don't know why TAD and HiC matrix did not overlay.

![Screen Shot 2020-07-16 at 12 27 39 AM](https://user-images.githubusercontent.com/19987406/87630659-3797af00-c6fb-11ea-98a6-b2e1a68ced33.png)

**Comment by lldelisle** [comment]
Hi,
The parameter names separated by `_` instead of space was in release 3.2.
You should update pyGenomeTracks or use old style ini file:
```

[tads]
file = tad_domains.bed
display = triangles
border color = black
title = tad
file_type = domains
color = none
height = 8
line width =  5
overlay previous = share-y

```

**Comment by YichaoOU** [comment]
Thanks!
