### ISSUE TITLE
Issue producing images with BED/GTF tracks

### ISSUE THREAD

**Issue by egmg726** [deeptools/pyGenomeTracks#273]
Using: Python 3.6.2 and pyGenomeTracks 3.5 

I'm having issues visualizing BED and GTF files, but I am not getting any error messages when I am trying to make an image. It will simply fail to produce a file. However, I have no issues producing files when using only BigWig files. I have tried this out with my own data and the test data on your GitHub page. (The examples below use files from the test_data folder in this repo)

For instance, if I use this command (with no BED or GTF files):

<pre><code>$ pyGenomeTracks --tracks alpha.ini --region X:2700000-3100000 --trackLabelFraction 0.2 --dpi 130 -o master_alpha.png</code></pre>
I will get this output (and an image):

<pre><code>INFO:pygenometracks.tracksClass:initialize 1. [test bigwig]
INFO:pygenometracks.tracksClass:initialize 2. [test bigwig max]
INFO:pygenometracks.tracksClass:initialize 3. [test bigwig mean]
INFO:pygenometracks.tracksClass:initialize 4. [spacer]
INFO:pygenometracks.tracksClass:initialize 5. [test bigwig]
INFO:pygenometracks.tracksClass:initialize 6. [test bigwig max]
INFO:pygenometracks.tracksClass:initialize 7. [test bigwig mean]
INFO:pygenometracks.tracksClass:initialize 8. [spacer]
INFO:pygenometracks.tracksClass:initialize 9. [test bigwig]
INFO:pygenometracks.tracksClass:initialize 10. [test bigwig mean]
INFO:pygenometracks.tracksClass:initialize 11. [test bigwig min]
INFO:pygenometracks.tracksClass:initialize 12. [x-axis]
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:0.007485389709472656
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 25.398936170212767. Dpi is set to 130

INFO:pygenometracks.tracksClass:plotting 1. [test bigwig]
INFO:pygenometracks.tracksClass:plotting 2. [test bigwig max]
INFO:pygenometracks.tracksClass:plotting 3. [test bigwig mean]
INFO:pygenometracks.tracksClass:plotting 4. [spacer]
INFO:pygenometracks.tracksClass:plotting 5. [test bigwig]
INFO:pygenometracks.tracksClass:plotting 6. [test bigwig max]
INFO:pygenometracks.tracksClass:plotting 7. [test bigwig mean]
INFO:pygenometracks.tracksClass:plotting 8. [spacer]
INFO:pygenometracks.tracksClass:plotting 9. [test bigwig]
INFO:pygenometracks.tracksClass:plotting 10. [test bigwig mean]
INFO:pygenometracks.tracksClass:plotting 11. [test bigwig min]
INFO:pygenometracks.tracksClass:plotting 12. [x-axis]</code></pre>

However, if I use a command like (with either BED or GTF tracks in it):

<pre><code>$ pyGenomeTracks --tracks bed_and_gtf_tracks.ini --region X:3000000-3300000 --trackLabelFraction 0.2 --width 38 --dpi 130 -o master_bed_and_gtf.png</code></pre>

I will get (and no image):

<pre><code>INFO:pygenometracks.tracksClass:initialize 1. [x-axis]
INFO:pygenometracks.tracksClass:initialize 2. [spacer]
INFO:pygenometracks.tracksClass:initialize 3. [genes 2]</code></pre>

It seems to just stop at the BED file and then not continue on with making an image. I've tried this on two different machines with multiple versions of Python/pyGenomeTracks but the same error appears. I'm unsure why this error is occurring so any help sorting this out would be much appreciated!

**Comment by lldelisle** [comment]
Hi,
I am on holiday until August 25th. Would you mind to provide a small bed which would fail to check when I am back?
Thanks

**Comment by lldelisle** [comment]
Hi,
Sorry, now I understand that you used the example.
I think the issue is that bedtools is not installed however the last version of pgt uses bedtools to speed up.
Thanks for reporting the bug. We will fix it in the next release.

**Comment by egmg726** [comment]
Loading bedtools into my environment did fix the issue for me. Thanks!
