### ISSUE TITLE
No PDF document generated

### ISSUE THREAD

**Issue by SMorrison42** [deeptools/pyGenomeTracks#278]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [ ] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [ ] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.

pyGenomeTracks verison 3.5

python version 3.7

  - [ ] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).
pyGenomeTracks --tracks tracks.ini --BED test.bed -o test.pdf

  - [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).
INFO:pygenometracks.tracksClass:initialize 1. [x-axis]
INFO:pygenometracks.tracksClass:initialize 2. [spacer]
INFO:pygenometracks.tracksClass:initialize 3. [test]

No PDF file is generated after the pyGenomeTracks command is generated

**Comment by lldelisle** [comment]
Hi,
Thanks for the report.
It may be that bedtools is not accessible in your environment like in #273 
If bedtools was accessible, please could you give more details on the ini file and the file in the [test] section?

**Comment by yanchunzhang** [comment]
> Hi,
> Thanks for the report.
> It may be that bedtools is not accessible in your environment like in #273
> If bedtools was accessible, please could you give more details on the ini file and the file in the [test] section?

This is very helpful! I got the same problem and was a little disappointed until I saw this answer. Could you please tell users to load bedtools in their environment before running pyGenomeTracks in your documentation or tutorial page? I think that'll help other users like me and the questioner.

**Comment by lldelisle** [comment]
It will be solved in the next version:
You would have a message: 
"It seems that BEDTools is not installed. Cannot subset the file." I can also add it to the documentation.

**Comment by lldelisle** [comment]
Hi,
The new version 3.5.1 take care of this.
