### ISSUE TITLE
Error in narrowPeak format

### ISSUE THREAD

**Issue by silvewheat** [deeptools/pyGenomeTracks#28]
Hello, 
         There is an example of using MACS2 narrowPeak format in README. But it seems don't work when I try to use "make_tracks_file" to produce .ini file. Error like this:
![image](https://user-images.githubusercontent.com/19344997/40952784-5aa89150-68af-11e8-8396-64a25e8cb31c.png)
         So, I try to add the configuration into .ini manually, like this:
![image](https://user-images.githubusercontent.com/19344997/40952864-bfa91f98-68af-11e8-83d2-d5b3773e2faf.png)
         But still doesn't work:
![image](https://user-images.githubusercontent.com/19344997/40952875-d3b4e60c-68af-11e8-912f-71eab48a43df.png)

**Comment by silvewheat** [comment]
I use conda to install pyGenomeTracks.
Maybe not the lastest version?

**Comment by silvewheat** [comment]
I use pip to install from github, and the problem solved.
My be the version in conda should be upgraded.

**Comment by fidelram** [comment]
Thanks for the info. Glad to hear that your problem was solved.
