### ISSUE TITLE
How to draw with the same Y value

### ISSUE THREAD

**Issue by NathanInChina** [deeptools/pyGenomeTracks#281]
Hello，Developer, I am using this tool you developed recently for some methylation and ATAC-seq data visualization. But I found that when I draw multiple bigwig files, their y-axis is not uniform, so it is difficult to compare the differences of peaks. So I would like to ask, is there a way to unify the Y value of bigwig in multiple ini files. Hope to receive your reply soon, thank you.

**Comment by lldelisle** [comment]
Hi,
For the moment, there is no way to unify automatically all y axis to the same value but you can set the min/max value of the y axis in each section with:
```ini
[bigwig1]
file = bigwig1.bw
min_value = 0
max_value = 30

[bigwig2]
file = bigwig2.bw
min_value = 0
max_value = 30

```

**Comment by NathanInChina** [comment]
Ok,I will do it. Thank you





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deeptools/pyGenomeTracks"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 下午3:38
收件人:&nbsp;"deeptools/pyGenomeTracks"<pyGenomeTracks@noreply.github.com&gt;;
抄送:&nbsp;"郭鲜森"<626310558@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [deeptools/pyGenomeTracks] How to draw with the same Y value (#281)





 
Hi,
 For the moment, there is no way to unify automatically all y axis to the same value but you can set the min/max value of the y axis in each section with:
 [bigwig1] file = bigwig1.bw min_value = 0 max_value = 30 [bigwig2] file = bigwig2.bw min_value = 0 max_value = 30
