### ISSUE TITLE
Y-axis does not reflect values

### ISSUE THREAD

**Issue by adomingues** [deeptools/pyGenomeTracks#282]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [X] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [X] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
pyGenomeTracks 3.2
Python 3.6.9

  - [X] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

pyGenomeTracks --tracks tracks_full_03_perls_fish_probe.ini --fontSize 18 --region chr4:27654397-71659448 --outFileName figure/full_coverage_tracks_03.chr_perls_fish_probe.pdf

pyGenomeTracks --tracks tracks_full_03_perls_fish_probe_box.ini --fontSize 18 --region chr4:48253039-48267834 --outFileName figure/full_coverage_tracks_03.chr_perls_fish_probe_zoom_in_box.pdf

  - [X] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

**The issue**

I am plotting several bigwig tracks for a very large genomic region, and then the same tracks but zoomed in. The issue is that the max value in the zoomed in version appears to be correct as it and matches what I see in IGV when loading the same tracks (about 1):

![igv_chr4_zoomin](https://user-images.githubusercontent.com/2607577/93823881-d8a66700-fc62-11ea-9473-7039b9a3f6a7.png)
[full_coverage_tracks_03.chr_perls_fish_probe_zoom_in.pdf](https://github.com/deeptools/pyGenomeTracks/files/5258252/full_coverage_tracks_03.chr_perls_fish_probe_zoom_in.pdf)

However, when the large region is plotted an issue becomes apparent: the max signal still peaks at one, even though it is ~2.3 as seen in IGV. Also, the zoomed in region, highlighted by the vertical dotted line, seems to have a coverage of ~0.3, when it is ~1.
![igv_chr4_large](https://user-images.githubusercontent.com/2607577/93824030-160af480-fc63-11ea-83f1-724b8a1e8076.png)
[full_coverage_tracks_03.chr_perls_fish_probe.pdf](https://github.com/deeptools/pyGenomeTracks/files/5258258/full_coverage_tracks_03.chr_perls_fish_probe.pdf)

Could this be artefact of the coverage summarization? In both the large region and the zoom the number_of_bins is being set at 700. See example below. Am I missing something else?

Cheers.

```
wt_PGCs_10dpf.mergedRep]
file = wt_PGCs_10dpf_totalRNA.bw
title = PGCs 10dpf
height = 2
color = #31a354
alpha = 1
min_value = 0
max_value = 1
number_of_bins = 700
nans_to_zeros = true
summary_method = mean
show_data_range = true
file_type = bigwig
```

**Comment by lldelisle** [comment]
Hi,
Indeed this is an artefact of summary. I tested it with the bigwig provided in the test_data directory. On IGV, I have:
![image](https://user-images.githubusercontent.com/30404086/93853636-80985080-fcb4-11ea-83c9-25b4d5148d63.png)
On pyGenomeTracks, I need to use number_of_bins = 2000 to have the same height:
```ini
[test]
file = bigwig_chrx_2e6_5e6.bw
title = bigwig_chrx_2e6_5e6 700 bins
height = 2
color = #31a354
alpha = 1
min_value = 0
max_value = 57
number_of_bins = 700
nans_to_zeros = true
summary_method = mean
show_data_range = true
file_type = bigwig

[test2]
file = bigwig_chrx_2e6_5e6.bw
title = bigwig_chrx_2e6_5e6 2000 bins
height = 2
color = #31a354
alpha = 1
min_value = 0
max_value = 57
number_of_bins = 2000
nans_to_zeros = true
summary_method = mean
show_data_range = true
file_type = bigwig
```

```bash
$ pgt --tracks test.ini --region chrX:2-11,318,247 -o test.png --dpi 500
```

![test](https://user-images.githubusercontent.com/30404086/93853739-b2a9b280-fcb4-11ea-9695-50bcefae4ec4.png)

However, if you want to see the peaks, I would recommend to use `summary_method = max`, this way, the peaks have the same height whatever the zoom is (however, you need to adjust the scale):
```ini
[test]
file = bigwig_chrx_2e6_5e6.bw
title = bigwig_chrx_2e6_5e6 700 bins
height = 2
color = #31a354
alpha = 1
min_value = 0
max_value = 57
number_of_bins = 700
nans_to_zeros = true
summary_method = mean
show_data_range = true
file_type = bigwig

[test2]
file = bigwig_chrx_2e6_5e6.bw
title = bigwig_chrx_2e6_5e6 2000 bins
height = 2
color = #31a354
alpha = 1
min_value = 0
max_value = 57
number_of_bins = 2000
nans_to_zeros = true
summary_method = mean
show_data_range = true
file_type = bigwig

[test3]
file = bigwig_chrx_2e6_5e6.bw
title = bigwig_chrx_2e6_5e6 700 bins max
height = 2
color = #31a354
alpha = 1
min_value = 0
max_value = 400
number_of_bins = 700
nans_to_zeros = true
summary_method = max
show_data_range = true
file_type = bigwig
```

```bash
$ pgt --tracks test2.ini --region chrX:2-11,318,247 -o test2.png --dpi 500
```

![test2](https://user-images.githubusercontent.com/30404086/93854173-88a4c000-fcb5-11ea-967f-8e3cbdb83915.png)

**Comment by adomingues** [comment]
Cheers @lldelisle . I am playing around with the settings but I got the gist now and it's only a matter of getting it right.

> However, if you want to see the peaks, I would recommend to use summary_method = max, this way, the peaks have the same height whatever the zoom is (however, you need to adjust the scale):

I don't need the peaks, in fact I would rather smooth them because those are very small regions, possibly with extremely high expression - outliers - and it's mess up the visualization :)

Thank you for your help.
