### ISSUE TITLE
how to presenet unique genes

### ISSUE THREAD

**Issue by benxiahu** [deeptools/pyGenomeTracks#285]
I used pyGenomeTracks to plot heatmap. However, there are the same genes showing multiple times. Do you know how to present one time per gene?

![image](https://user-images.githubusercontent.com/12387462/94308994-60cb8b80-ff45-11ea-941d-b4b8a2830105.png)

Thanks

**Comment by lldelisle** [comment]
Hi,
If it is a gtf use:
```ini
merge_transcripts = true
```

**Comment by benxiahu** [comment]
it is a bed file

**Comment by lldelisle** [comment]
Then, I am sorry but this is not part of pyGenomeTracks. I suggest that you preprocess your bed to merge all transcripts in one or you find a gtf that has similar annotations.
