### ISSUE TITLE
Installation fails with python 3.8

### ISSUE THREAD

**Issue by mffrank** [deeptools/pyGenomeTracks#293]
```
python=3.8
pygenometracks=3.5.1
```
Hi, many thanks for creating this great package!
I am having trouble installing the current Version with python 3.8.
## Command 
```
conda create -n pygenometracks -c bioconda -c conda-forge pygenometracks python=3.8
```
## Output
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                            

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.8
pygenometracks -> python[version='2.7.*|3.5.*|3.6.*|<3.7|>=3.6|>=3.6,<3.7.0a0|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
pygenometracks -> future[version='>=0.17.0'] -> python[version='3.4.*|>=3|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|<3.0.0|>=3.5']
```

**Comment by lldelisle** [comment]
Hi,
When I dig on this question I realized that `pairix` which is a dependency cannot be install with python 3.8. I wrote an issue to the pairix repo but I have not got any answer yet: https://github.com/4dn-dcic/pairix/issues/64

**Comment by joachimwolff** [comment]
@mffrank As it is written in our release notes, Python 3.8 is not officially supported by us. Please use Python 3.7 or 3.6. Thank you!

**Comment by mffrank** [comment]
Thank you for the super quick response! I will use 3.7 for now. Could I suggest adding the requirement for python <=3.8 to the Installation instructions in the README for now? At the moment it just says >=3.6

**Comment by lldelisle** [comment]
pygenometracks can now be installed on python 3.8 with conda and we officially support it.
