### ISSUE TITLE
pip installation fails because HiCMatrix 15 is not online

### ISSUE THREAD

**Issue by mffrank** [deeptools/pyGenomeTracks#294]
```
python=3.8
pygenometracks=3.5.1
```

Pip cannot find version 15 of HiCMatrix which is required for the current pygenometracks version.

## Command
```
## Fresh environment
conda create -n pygenometracks -c bioconda -c conda-forge python=3.8
conda activate pygenometracks
pip install pyGenomeTracks
```
## Output
```
Collecting pyGenomeTracks
  Using cached pyGenomeTracks-3.5.1-py2.py3-none-any.whl (93 kB)
Collecting matplotlib==3.1.1
  Downloading matplotlib-3.1.1.tar.gz (37.8 MB)
     |████████████████████████████████| 37.8 MB 1.6 MB/s 
Collecting gffutils>=0.9
  Using cached gffutils-0.10.1.tar.gz (1.5 MB)
ERROR: Could not find a version that satisfies the requirement hicmatrix>=15 (from pyGenomeTracks) (from versions: 5, 7, 10, 11, 12, 13)
ERROR: No matching distribution found for hicmatrix>=15 (from pyGenomeTracks)

```

**Comment by joachimwolff** [comment]
Hi,

conda is our preferred way of distributing pyGenomeTracks, pip is always a bit behind. In this case we have not uploaded the newest hicmatrix version to pip so far. I will try to take care of it today, anyway, simply use conda and python 3.7 to install pyGenomeTracks if you don't want to wait for us to provide the necessary updates.

Best,

Joachim

**Comment by lldelisle** [comment]
Hi,
HiCMatrix has been published on pip.
Thanks for the report.
