### ISSUE TITLE
pyGenomeTracks should be able to visualized BED6+4 format? 

### ISSUE THREAD

**Issue by zfrenchee** [deeptools/pyGenomeTracks#3]
Hello pyGenomeTracks developers. 

I'd like to visualize the results of an ATAC-Seq run, which is a narrowPeaks file from MACS2. [Here's the reference about the narrowPeaks BED6+4 format](https://genome.ucsc.edu/FAQ/FAQformat.html#format12). 

The first 6 are the expected fields, the next 4 are: 
> - signalValue - Measurement of overall (usually, average) enrichment for the region.
> - pValue - Measurement of statistical significance (-log10). Use -1 if no pValue is assigned.
> - qValue - Measurement of statistical significance using false discovery rate (-log10). Use -1 if no qValue is assigned.
> - peak - Point-source called for this peak; 0-based offset from chromStart. Use -1 if no point-source called.

These can potentially be ignored, as a first pass, and the file can be visualized as a BED6. Unfortunately, current behavior is: 

```
AssertionError: File type detected is bed6 but line 2: chr1	10003	10466	HC1_peak_1	2075	.	18.13246	212.86768	207.53099	73
 does not have 6 fields.
```

Note: @dpryan79 If you think there's a better tool for visualizing tracks resulting from ChIP/ATAC/DNase (callable from a python program, ideally not on the web) then I'm happy to ignore this issue and use that other tool. But This might be a quick fix...? https://github.com/deeptools/pyGenomeTracks/blob/c858168f5f6474a6760d9ccc1174cc00f22eaee9/pygenometracks/readBed.py#L172-L174

**Comment by zfrenchee** [comment]
I solved my use case for this by using bigwigs instead. This might still be worth doing though. 

Thanks for this great software!

**Comment by fidelram** [comment]
The issue is that the BED6 +4 output from MACS2 is not standard BED format as defined by UCSC (https://genome.ucsc.edu/FAQ/FAQformat.html#format1).

As you mentioned, you can use bigwig files to plot the scores that you want. That would be my recommended solution.

**Comment by zfrenchee** [comment]
@fidelram this caused me an issue again today. I wanted to plot the bigwig tracks and bed peaks called by MACS2 in conjunction, to try to better understand how MACS2 is calling peaks. You can see that the MACS2 format _is_ a standard format defined by UCSC: https://genome.ucsc.edu/FAQ/FAQformat.html#format12 and therefore I think it may make sense for pyGenomeTracks to support it

**Comment by fidelram** [comment]
Thanks for the link. The narrowPeak format is not supported. Simply convert
it to bed: `cut -f 1-6 macs_output.narrowPeak > macs_output.bed` See:
https://www.biostars.org/p/273912/

**Comment by zfrenchee** [comment]
Thanks @fidelram !

**Comment by fidelram** [comment]
This comment is to let you know that I added support for .narrowPeaks format. You can see an example output on the readme file.

**Comment by zfrenchee** [comment]
Hooray!! Thanks @fidelram !
