### ISSUE TITLE
Arcs color scale based on score

### ISSUE THREAD

**Issue by gtrichard** [deeptools/pyGenomeTracks#30]
Hello @fidelram and @vivekbhr ,

I started using pyGenomeTracks and I really enjoy it, thanks for the hard work 👍 

Would it be possible to use the last column of test.arcs file (https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/test.arcs) as a basis for a color scale of the arcs in order to display, for example, the interaction strength between 2 loci?

https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/test.arcs

Best,
Gautier

**Comment by DonStephano** [comment]
The newest version of pyGenomeTracks is very very useful and saves a lot of time!

@gtrichard s idea of the color-scale would is great and would be a cool feature. For us it would be also helpful to add a rgb-based-column so that each arc or a previously specified group of arcs (i.e. all interactions from a promotor) is plotted in a separate color (see example).

![test](https://user-images.githubusercontent.com/32867294/43714968-325c1d7e-997f-11e8-8bc8-bd30ece16763.png)

**Comment by YichaoCaiDBS** [comment]
I am diving into the pyGenomeTracks and I found it very useful! Thanks a lot for the tool!

After digging into the enhancements that you are currently working on (#102), I found that the color-scale based on the score column has been added into the pull request.
Is it possible to add in the feature of using additional columns in .arc file for customization of the plotting style? That would be super useful.

For example,
```
# chrom1    start1    end1    chrom2    start2    end2    score    [additional column]
chr1    1    100    chr1    501    600    4    red
chr1    201    300    chr1    501    600    4    blue
```

Use the addition column as the attribute of the color when doing the plotting. Something like assigning colors to different levels of factors in R/ggplot2.

For example, if the 'color' field in .ini file specified as a color map name, scores are used to scale color to each arc (which has been included in the pull request #102 ). If the 'color' field in .ini file specified as 'predefined', the additional column would be used as the predefined color when calling `plot_arcs()`.

For further versatile plotting, would you consider including user pre-defined attributes if it is possible? For example, include a field of 'additionalColumn' in .ini file to be used as the key of the additional column to be used in `self.properties` that overrides the default value.
For example, in .arc file:
```
chr1    1    100    chr1    501    600    4    red    dotted
chr1    201    300    chr1    501    600    4    blue    dashed
```
In .ini file:
```
[test arcs]
file = test.arcs
title = links orientation=inverted
orientation = inverted
line style = dashed
height = 2
additionalColumn = ["color", "line style"]
```
To use the additional column to override the original value, `self.properties["color"] = ["red", "blue"]` and `self.properties["line style"] = ["dotted", "dashed"]`.

These are just some thoughts that I think would be good to have. I don't have the experience of developing such tools in Python, so please bear with me if I raise anything that is impossible to implement.

**Comment by bgruening** [comment]
@YichaoCaiDBS we will release soon a new version and this issues should be fixed. If you have further requests can you please add a new issue? I gonna close this one now.

**Comment by Benfeitas** [comment]
There seems to be a problem as, regardless of the score value that I have, and even considering score values the same as in [the example case](https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/test.arcs), I always end up with an error in the color mapping in matplotlib, eeven when considering the same colormap as in the example:


```
Traceback (most recent call last):
  File "/usr/local/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/usr/local/lib/python3.7/site-packages/pygenometracks/plotTracks.py", line 307, in main
    trp.plot(args.outFileName, *region, title=args.title)
  File "/usr/local/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 241, in plot
    track.plot(plot_axis, chrom, start, end)
  File "/usr/local/lib/python3.7/site-packages/pygenometracks/tracks/LinksTrack.py", line 143, in plot
    self.plot_arcs(ax, interval)
  File "/usr/local/lib/python3.7/site-packages/pygenometracks/tracks/LinksTrack.py", line 172, in plot_arcs
    linewidth=self.line_width, ls=self.properties['line style']))
  File "/usr/local/lib/python3.7/site-packages/matplotlib/patches.py", line 1633, in __init__
    Ellipse.__init__(self, xy, width, height, angle, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/patches.py", line 1474, in __init__
    Patch.__init__(self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/patches.py", line 79, in __init__
    self.set_color(color)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/patches.py", line 334, in set_color
    self.set_facecolor(c)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/patches.py", line 319, in set_facecolor
    self._set_facecolor(color)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/patches.py", line 307, in _set_facecolor
    self._facecolor = colors.to_rgba(color, alpha)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/colors.py", line 177, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/colors.py", line 233, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 'RdYlGn'
```
