### ISSUE TITLE
Possible python color names?

### ISSUE THREAD

**Issue by Zepeng-Mu** [deeptools/pyGenomeTracks#307]
pyGenomeTracks --version
pyGenomeTracks 3.5

Hi, I am wondering whether there is a list of available colors for `color`.  I tried some colors on this page: https://matplotlib.org/3.1.0/gallery/color/named_colors.html but some are not working, therefore it would be nice to know which colors can be recognized.

Thanks so much!

**Comment by lldelisle** [comment]
Hi,
Oups, I thought they were all working... Could you tell us which one did not work (with which version of matplotlib) so we can investigate this issue?
Thanks

**Comment by Zepeng-Mu** [comment]
Hi, I went back to check and found that I may have misspelled the color name! It is working now. Really sorry about this!
