### ISSUE TITLE
how to specify the resolution of a mcool file?

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/pyGenomeTracks#318]
I couldn't find it in the documentation. how could I specify the resolution of my mcool file to be used in the plots?

**Comment by lldelisle** [comment]
Hi,
I am really sorry for the delay I did not received notification...
You can find an example here: 
https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/mcool.ini
