### ISSUE TITLE
difference between bigwig tracks

### ISSUE THREAD

**Issue by Phlya** [deeptools/pyGenomeTracks#32]
Hi,

Would be really cool if it was possible to subtract one track from another and show difference between them. Or log ratio. I suppose, ideally any mathematical operations :) Thanks!

Ilya

**Comment by dpryan79** [comment]
See `bigwigCompare` from deepTools and `wiggletools` as ways to preprocess your data, though I realize doing this sort of thing on the fly would be nice.

**Comment by Phlya** [comment]
Yeah, thanks, I have found it actually, but yes, on the fly would be very convenient.

**Comment by Phlya** [comment]
And a related to that question is would it be possible to have a different colour for negative values? I think currently there is no such option, looking at the code?

**Comment by fidelram** [comment]
The way to have different colors is to set two tracks with no space in
between. For the upper track you set the scale from 0 to 'auto' or any
other value, for the lower track you set the scale from 'auto' to 0. Each
track can have it's own color.

**Comment by Phlya** [comment]
Thanks! Yeah, that's possible, but seems a little hacky to me, and it's especially complicated since I am using pygenometracks as a library and would also need to set up the axes manually... I think I could quite easily add the negative colour option to pygenometracks - if I do, would you consider a PR for this?

**Comment by fidelram** [comment]
Sure, If you can do such a thing I will be happy to merge.

**Comment by lldelisle** [comment]
After nearly 2 years, this is in version 3.4
