### ISSUE TITLE
Hic data is not shown

### ISSUE THREAD

**Issue by yancychy** [deeptools/pyGenomeTracks#320]
Hi, 
    I tired to view the hic data using hicPlotTADs. My track.ini is referring the link of 
https://pygenometracks.readthedocs.io/en/latest/content/examples.html#examples-with-hi-c-data.
    The plot is like a line. The hic data is viewed as a line. The figure is shown in (please paste it to the web browser)
 [https://drive.google.com/file/d/1g47R3nvGyssyH4g9dnPbRnwxR9B966il/view?usp=sharing](url)
 
track.ini content is as follows. I am not sure what's wrong with my configuration. Could you help me to solve it? Thanks very much.
> [hic matrix]
file = Biotin_1000_norm.h5
title = Hi-C Biotin 
depth = 1000 
file_type = hic_matrix
show_masked_bins = false
[tads]
file = Biotin_1000_norm_domains.bed
display = triangles
border_color = black
color = none 
overlay_previous = share-y

**Comment by lldelisle** [comment]
Hi,
I guess this one is solved, seee https://github.com/deeptools/HiCExplorer/issues/653.
If it is not the case, do not hesitate to reopen it.
