### ISSUE TITLE
outFileName is not only prefix if --BED

### ISSUE THREAD

**Issue by mirax87** [deeptools/pyGenomeTracks#324]
Dear pyGenomeTracks developers,

after talking to @LeilyR, I have an issue to report.

I was using pyGenomeTracks to plot multiple regions at once using `--BED` and tried using `--outFileName` as prefix. Unfortunately, it kept complaining that the constructed path was malformatted (could find folder or something like that).After several trial and error runs, it turned out that the `--outFileName` for the `--BED` case still requires the file format as suffix, i.e. `--outFileName <prefix>.png`, otherwise it will fail.

I am using pyGenomeTracks version 3.4 and installed it through conda.

----

PS: I am currently trying to visualize back-splicing junction from circRNA using the link files. It's hard to find software to do that in such a flexible manner as pyGenomeTracks can. Great tool! Thanks

**Comment by lldelisle** [comment]
Thanks, we need to improve the documentation.

**Comment by LeilyR** [comment]
I was thinking that we generate png plots by default if no extension , and maybe have a param for the extension. Similar to what we have in deeptools.
