### ISSUE TITLE
Set max value using mean and strand deviation for bigwig track

### ISSUE THREAD

**Issue by arpanda** [deeptools/pyGenomeTracks#325]
For the bigwig track, if we don't specify the max_value, it automatically set the max value to `max`. So instead of max, is it possible to set the max value using mean and standard deviation. like 
```
max_value = mean + 2 * standard deviation
```

Also I was trying to change the fontsize of title using `fontsize=10` and it gives me the below warning.

```
WARNING:pygenometracks.tracksClass:In section 1. [bigwig file], these parameters are unused:['fontsize'].

```
So is it possible to change the font size of the title for a bigwig track?

**Comment by lldelisle** [comment]
Hi,
Thanks for using pyGenomeTracks. For the moment, it is not possible to set such `max_value`. The easiest way is to compute it is to compute it before writing the ini file (unfortunately it will not adjust to the plotted region):
```
my_max=$(python -c "import pyBigWig;bw = pyBigWig.open('blabla.bw');print(bw.stats('chr2', 71000000,78000000)[0] + 2 * bw.stats('chr2', 71000000,78000000, type='std')[0])")
echo "[bigwig]
file = blabla.bw
max_value = $my_max
" > blabla.ini
```

For the font size, if you are refering to the title and y lim values, you need to change the font size of the whole image:
```
pyGenomeTracks --fontSize 10 ...
```

**Comment by arpanda** [comment]
Thanks for the idea
