### ISSUE TITLE
Integrate with matplotlib?

### ISSUE THREAD

**Issue by gabedolpten** [deeptools/pyGenomeTracks#328]
Hi,
Let's say I already have a matplotlib plot ready (that I am generating programatically for 30 different loci)
Is there some way to pass this figure/axis into pyGenomeTracks so that pyGenomeTracks plots it into that specific figure? Or vice versa?

**Comment by lldelisle** [comment]
Hi,
Unfortunately for the moment we do not support api. However, you can read some hints from https://github.com/deeptools/pyGenomeTracks/issues/20...

**Comment by gabedolpten** [comment]
Thanks :-)
