### ISSUE TITLE
Need help with making a tracks file

### ISSUE THREAD

**Issue by LuminescentBeing** [deeptools/pyGenomeTracks#329]
Hello,

I am attempting to analyze Hi-C data and I want to plot the TADs. First, I need to make a tracks file, but I am not sure how to make it with the parameters shown here: 

```
[x-axis]
where = top

[hic matrix]
file = hic_data.h5
title = Hi-C data
# depth is the maximum distance plotted in bp. In Hi-C tracks
# the height of the track is calculated based on the depth such
# that the matrix does not look deformed
depth = 300000
transform = log1p
file_type = hic_matrix

[tads]
file = domains.bed
file_type = domains
border_color = black
color = none
# the tads are overlay over the hic-matrix
# the share-y options sets the y-axis to be shared
# between the Hi-C matrix and the TADs.
overlay_previous = share-y

[spacer]

[bigwig file test]
file = bigwig.bw
# height of the track in cm (optional value)
height = 4
title = ChIP-seq
min_value = 0
max_value = 30

```

I am currently using the following code
``make_tracks_file -f replicateMerged.Corrected_20kb.h5 marks_et-al_TADs_20kb-Bins_domains.bed hg19_genes_sorted.bed -o tracks.ini``

It ran completely, but I want it to have the above parameters.

I have pyGenomeTracks version 3.6.

I am new to coding, so I would appreciate any help. I looked at other issues, but I haven't been able to figure it out. 

Thanks in advance!

**Comment by lldelisle** [comment]
Hi,
Thanks for using pyGenomeTracks. In fact there are 2 ways to generate a tracks file:
- You know what you want and you set it manually
- You don't know what you can you with your file so you use `make_tracks_file`.

I think you know what you want and what you provided is very good. You just need to adapt your file to match your file names, so:

```ini
[x-axis]
where = top

[hic matrix]
file = replicateMerged.Corrected_20kb.h5
title = Hi-C data
# depth is the maximum distance plotted in bp. In Hi-C tracks
# the height of the track is calculated based on the depth such
# that the matrix does not look deformed
depth = 300000 # 300kb is very small if you want to see TADs you may want to increase this number
transform = log1p
file_type = hic_matrix

[tads]
file = marks_et-al_TADs_20kb-Bins_domains.bed
file_type = domains
border_color = black
color = none
# the tads are overlay over the hic-matrix
# the share-y options sets the y-axis to be shared
# between the Hi-C matrix and the TADs.
overlay_previous = share-y

[spacer]

# If you want to add a track with your genes:
[genes]
file = hg19_genes_sorted.bed
height = 5

# Apparently you don't have bigwig so I would comment that:
# [bigwig file test]
# file = bigwig.bw
# # height of the track in cm (optional value)
# height = 4
# title = ChIP-seq
# min_value = 0
# max_value = 30
```

Then you need to run pyGenomeTracks to see your plot:
```
pyGenomeTracks --tracks your.ini --region chrBlaBla-Start:End -o your.png
```

Don't hesitate to check our [documentation](https://pygenometracks.readthedocs.io) to see the possible options.

**Comment by LuminescentBeing** [comment]
Thank you so much for the assistance! To create the file, I just have to make a text document and insert those parameters inside it? I am just confused on that part. Am I supposed to use Python to make the file?

Sorry if the questions are basic. I am just unfamiliar with making files.

**Comment by lldelisle** [comment]
No problem, yes just create a text file (not a word document, nor rtf, just a plain text file) and copy what I put into code block into it. No need of python to do that.

**Comment by LuminescentBeing** [comment]
Okay, that answered all of my questions. Thank you so much again for clearing that up!
