### ISSUE TITLE
Location of bed labels

### ISSUE THREAD

**Issue by celinasjose** [deeptools/pyGenomeTracks#330]
Hi,
I am using pyGenomeTracks 3.5.
I have a bed file with a set of locations, with a different label for each, in collapse display.
Is it possible to put the label of each location below each location, instead of on the side?

Thanks

**Comment by lldelisle** [comment]
Hi,
Unfortunately no, this is not an option for the moment... We can add it to the list of features to integrate...

**Comment by celinasjose** [comment]
Thank you for your fast response.
I think it would be useful to use the colapse display without label sobreposition.

Further, it is possible to have a links track with different colors between lines?

Thanks

**Comment by lldelisle** [comment]
To remove the labels just use:
`labels = false`
To use different colors, for links, if they have a score, you can use:
`color = RdYlGn # or an other valid colormap`

**Comment by lldelisle** [comment]
Feel free to reopen this issue if you still have questions.
