### ISSUE TITLE
 parameter operation

### ISSUE THREAD

**Issue by ZunpengLiu** [deeptools/pyGenomeTracks#331]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [ ] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [ ] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
pyGenomeTracks 3.3
Python 3.7.7

  - [ ] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

[test bigwig1]
file = CpG.H9.bw
second_file = CpG.W9.bw
color = blue
height = 4
title = first bw
min_value = 0
max_value = 3

[test bigwig2]
file = CpG.W9.bw
color = red
height = 4
title = second bw
min_value = 0
max_value = 3
orientation = inverted

[spacer]
height = 0.5

[test bigwig dif]
file = CpG.H9.bw
second_file = CpG.W9.bw
color = blue
negative_color = red
height = 8
title = operation = file - second_file
operation = file - second_file
min_value = -3
max_value = 3
nans_to_zeros = true

  - [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

![image](https://user-images.githubusercontent.com/31592626/111826544-c3fe0f80-8923-11eb-9526-3f8fc3465103.png)

Dear Sir,

Thanks for your management of this powerful tool! I have a issue about the the parameter "operation" which can make operations between one or two files as the manual mentioned.

However, I found that the processed track (file -second file) is the original track of file 1.After many attempts, this is still the case.  So, do you have any suggestion？

Thanks for your help!

Zunpeng

**Comment by ZunpengLiu** [comment]
I also downloaded the test data from the GitHub, then repeated the given processing script as follows,

`[test bigwig1]
file = bigwig_chrx_2e6_5e6.bw
second_file = bigwig2_X_2.5e6_3.5e6.bw
color = blue
height = 4
title = first bw
min_value = 0
max_value = 30

[test bigwig2]
file = bigwig2_X_2.5e6_3.5e6.bw
color = red
height = 4
title = second bw
min_value = 0
max_value = 30
orientation = inverted

[spacer]
height = 0.5

[test bigwig dif]
file = bigwig_chrx_2e6_5e6.bw
second_file = bigwig2_X_2.5e6_3.5e6.bw
color = blue
negative_color = red
height = 8
title = operation = file - second_file
operation = file - second_file
min_value = -30
max_value = 30
nans_to_zeros = true

[spacer]
height = 0.5`


However, the track I obtained is different form the example track in Github. The operated track is also same as  the original track of file 1.


![image](https://user-images.githubusercontent.com/31592626/111866036-74f8be80-89a5-11eb-9870-b2eb13f7ae3e.png)

**Comment by lldelisle** [comment]
Hi,
The `operation` has been introduced in version [3.4](https://pygenometracks.readthedocs.io/en/latest/content/releases/3.4.html). You need to upgrade pyGenomeTracks to use this functionality...
