### ISSUE TITLE
TAD annotation colors

### ISSUE THREAD

**Issue by mujahida87** [deeptools/pyGenomeTracks#336]
Hi, I tried to color the TADs according to my TAD annotation (e.g. active, silent, PcG). But I can't see my given color in the output image. Can you please have a look at my input file, if the given format is correct? Than you

1) --version pyGenomeTracks 3.6, Python 2.7.5

2) my command: 
/apps/hicexplorer/3.6/bin/pyGenomeTracks --tracks tracks.ini --region X:6000000-9000000 --trackLabelFraction 0.2 --width 38 --dpi 130  -o plot.png

3) input my file >
![Screenshot 2021-04-26 at 11 31 24](https://user-images.githubusercontent.com/30443593/116061258-f3bad880-a682-11eb-8075-9b9c389d6239.png)
4) output image> 
![Screenshot 2021-04-26 at 11 34 21](https://user-images.githubusercontent.com/30443593/116061637-63c95e80-a683-11eb-8eba-a9786a379c2f.png)

**Comment by lldelisle** [comment]
Hi,
I think you did not set the color of the TAD track:
`color = bed_rgb`
See https://pygenometracks.readthedocs.io/en/latest/content/examples.html#examples-with-multiple-options

**Comment by mujahida87** [comment]
yes, it's sorted. Thank you much

**Comment by lldelisle** [comment]
I see that you also used the 5th field (score), if you want to use this field you need to use a colormap as a color:
`color = Reds`
