### ISSUE TITLE
Italic for gene labels

### ISSUE THREAD

**Issue by Zepeng-Mu** [deeptools/pyGenomeTracks#338]
Hi, I just have a minor point. Since in many species, especially mouse and human, gene labels should be italic, is there a way to specify this in GTF or BED track? Of course I can just edit the output PDF file for publication. But it would be great if there is a way to do this while plotting.

Thanks!!

**Comment by lldelisle** [comment]
Hi,
Good idea, is your idea to make all labels of the track in italic or are you more thinking of a way to have some labels in italic and some not? For example, interpreting `italic(xx)` as *xx*?

**Comment by Zepeng-Mu** [comment]
Hi, in my case I'm plotting the gene labels directly from a GTF file, so I'm not sure whether it is easy to use `italic()` option. But I can imagine other users may want more control. For GTF track, I think maybe adding an option similar to `italic = true` (so that all labels are italic) would be sufficient.
Thanks!

**Comment by lldelisle** [comment]
Hi,
I wrote the code for the italic. For the moment, it is [here](https://github.com/lldelisle/pyGenomeTracks/tree/geneit). To use italic, set `fontstyle = italic` as in the following example:

![master_bed_italic](https://github.com/lldelisle/pyGenomeTracks/raw/geneit/pygenometracks/tests/test_data/master_bed_italic.png)


[corresponding ini file](https://github.com/lldelisle/pyGenomeTracks/blob/geneit/pygenometracks/tests/test_data/bed_italic.ini)

**Comment by Zepeng-Mu** [comment]
Cool, thanks!

**Comment by lldelisle** [comment]
This has been integrated in version 3.7
