### ISSUE TITLE
Editable text

### ISSUE THREAD

**Issue by fmarletaz** [deeptools/pyGenomeTracks#339]
Thanks for this great tool! I have a question, maybe I missed something, but when I import the pdf or svg generated in a vector drawing software to assemble a figure, it is seen as a curve and not as text, and therefore is not editable. Is there a way to change that in the parameters? Thanks a lot!

**Comment by lldelisle** [comment]
Hi,
Would you mind to be more precise? Which text are you refering to? The labels of the tracks (title) or the axis or the labels of interval of bed track? In my hands, I am able to modify the texts of [this figure](https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/master_bedgraph_useMid.pdf) with inkscape.

**Comment by fmarletaz** [comment]
Sorry for the lack of precision. I am taking about all text element in the generated figure (labels and intervals). Thanks for pointing me to the sample figure. I guess my problem is that I was using adobe illustrator, I downloaded inkscape and it works there.

**Comment by lldelisle** [comment]
If I remember well, eps format may be more adapted to illustrator...
