### ISSUE TITLE
[Galaxy wrappers] Values of legend

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/pyGenomeTracks#34]
We have the issue that for very small chromsomes e.g. less than 1kb in total the legend shows only 0 instead of the correct values. 
Could be an issue with the `relableTicks` function.

**Comment by joachimwolff** [comment]
See PR #36

**Comment by bgruening** [comment]
@joachimwolff  please give the latest version a try. It should solve your issue.
You can try the newest version here: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/
