### ISSUE TITLE
Normalize bigwig track based on coverage

### ISSUE THREAD

**Issue by arpanda** [deeptools/pyGenomeTracks#344]
Hi,
I have few bigwig files with different coverage or read counts and I would like to plot it together. So is there a way to normalize the plots based on coverage or read count?

Thanks
Arijit

**Comment by lldelisle** [comment]
Hi,
I am not sure I understand what you want but you can use `operation`. For example, if you have 2 files with 2 and 3 million mapped reads respectively, you can do:
```ini
[bigwig1]
file = first.bw
operation = file / 2
min_value = 0
max_value = 10
[bigwig2]
file = second.bw
operation = file / 3
min_value = 0
max_value = 10
```

**Comment by arpanda** [comment]
Thanks. I was looking that information only.
In case of missing `max_value` parameter in merged tracks, max value automatically set from either first or last file. Multiple tracks are merged using  `overlay_previous = share-y`

Is it possible to automatically set the max value from the multiple tracks instead of specifying it? as In some cases, we do not know the max value. setting one such value, can be too small or high.

**Comment by lldelisle** [comment]
For the moment, no...
#321 also request group scaling which is roughly the same. You can find a temporary solution there.
I close the issue but you can reopen it.
