### ISSUE TITLE
pyGenomeTracks is slow for large files

### ISSUE THREAD

**Issue by alexlenail** [deeptools/pyGenomeTracks#357]
takes >30m to load the human reference genome gtf. 

Is there a way to speed this up? What about storing an intermediate representation (e.g. pickle?) or getting queried regions with tabix where possible?

**Comment by alexlenail** [comment]
E.g. would it be possible to set a permanent destination for the database, to use in a future call to pyGenomeTracks? 

https://github.com/deeptools/pyGenomeTracks/blob/ce2ec50b718f2094cd301d38ab8b531f54fb07bc/pygenometracks/readGtf.py#L64

**Comment by Zepeng-Mu** [comment]
I encountered the same problem before. I solution I chose is to convert the gtf to bed12 first.
Possibly duplicate of #241

**Comment by alexlenail** [comment]
There appears to be some sort of

**Comment by lldelisle** [comment]
Hi,
@alexlenail could you tell us which version you are using and how you installed it (pip or conda). Since version 3.5 we slice the gtf using bedtools and thus it should be quicker.

**Comment by alexlenail** [comment]
with pip

pyGenomeTracks==3.6
Python 3.7.10
pip 21.1.3
bedtools v2.27.1

**Comment by lldelisle** [comment]
Did you try to plot a large region?
