### ISSUE TITLE
X-axis ticks problem plotting short regions

### ISSUE THREAD

**Issue by carlosparq** [deeptools/pyGenomeTracks#363]
Hi there,
I'm using pyGenomeTracks 3.6 through a conda environment and I'm having some trouble understanding the ticks and values shown in the X-axis when plotting short regions (< 5-10 kb). I've attached a picture of an usual X-axis I generate. As you can see, it's very difficult to get a sense of the real coordinates in basepairs because it doesn't show decimal points, and the values seem randomly rounded up. In the examples provided in the website I see some show decimal points, and that would be great. Is there a way to do that?

![test](https://user-images.githubusercontent.com/25367900/130458495-ded87360-22b8-41e3-986b-0093accf5fcf.png)

Thank you!

**Comment by lldelisle** [comment]
Solved in version 3.7
