### ISSUE TITLE
Why does plotting a BED file leave a little dot next to the region?

### ISSUE THREAD

**Issue by alexlenail** [deeptools/pyGenomeTracks#364]
no style command in .ini:

![image](https://user-images.githubusercontent.com/2761597/132966068-fe14b858-175d-4346-ada7-6237b7f6bbdf.png)

style = UCSC

![image](https://user-images.githubusercontent.com/2761597/132966029-255a9683-f4de-41d6-bd2d-157ed1b50893.png)

style = tssarrow

![image](https://user-images.githubusercontent.com/2761597/132966039-b63764d4-d22a-4479-afc8-ff30ba5d6fe2.png)

BED file: 

```
chr11	46617120	46617360
chr11	47359700	47359940
chr11	47361180	47361324
chr11	47361200	47361400
chr11	47377132	47377320
chr11	47378493	47378681
chr11	47388126	47388347
chr11	47391100	47391320
chr11	47393167	47393420
chr11	47394800	47395000
chr11	47400147	47400740
chr11	47578900	47579120
chr11	47715160	47715420
chr11	47715290	47715500
chr11	48001840	48002050
chr11	48011998	48012233
```

**Comment by lldelisle** [comment]
Hi,
By default we fill the bed3 in bed6 with "." as name... This is historical... To remove this, you just need to put:
```
labels = false
```
