### ISSUE TITLE
change colors of line plot for bedgraph matrix

### ISSUE THREAD

**Issue by utao-cao** [deeptools/pyGenomeTracks#365]
Hi there, I try examples in configure and using a color name from [the recommended website](https://matplotlib.org/2.0.2/users/colormaps.html). These all failed 

```colormap = ['blue', 'yellow', 'red']
colormap = ['white', (1, 0.88, .66), (1, 0.74, 0.25), (1, 0.5, 0), (1, 0.19, 0), (0.74, 0, 0), (0.35, 0, 0)]
colormap = ['Purples']
colormap = 'Purples'
colormap = Purples
```
**My data**
```
chr7	99872600	99872700	100	74.605	100
chr7	99872800	99872900	72.835	49.435	51.1
chr7	99872900	99873000	42.346	40.158	40.893
chr7	99873000	99873100	0	0	0
```
and my **output** looks like this:

![image](https://user-images.githubusercontent.com/54352433/143727227-efe1406d-8fe6-4357-9ca7-89c59f82d99f.png)

**Besides**, I am curious about is these codes changes the default color viridis 
```
GenomeTrack.set_properties_defaults(self)
        if self.properties['type'] == 'matrix':
            self.process_color('colormap', colormap_possible=True,
                               colormap_only=True,
                               default_value_is_colormap=True)
            self.cmap = cm.get_cmap(self.properties['colormap'])
```

Actually, what I am **trying to achieve** is this example:
![image](https://user-images.githubusercontent.com/54352433/143727429-99039eb9-3eb9-49db-a472-d04bae8bef5b.png)

**Comment by utao-cao** [comment]
Maybe it should also fulfill the precondition:  
> If the type is not lines,  you can choose to keep the matrix as not rasterized

So I update my title.

**Comment by lldelisle** [comment]
Hi,
It is indeed unclear.
The colormap can only be set if you choose `type = matrix`. For the moment, you cannot choose the color for the `type = line`:
https://github.com/deeptools/pyGenomeTracks/blob/488a6d3f9e81c6ca1af9f90484445070ed9c7024/pygenometracks/tracks/BedGraphMatrixTrack.py#L120-L130
Each line is written in grey and the average is plot in the default color from matplotlib (blue).
How would you use the colormap? Each line a color from the colormap?

Thanks

**Comment by utao-cao** [comment]
Hi,Thanks for your quick support.  I thought colormap could change the color of average line if type == line. Anyway, it's still useful with heatmap.Thanks-------- 原始邮件 --------发件人： Lucille Delisle ***@***.***>日期： 2021年11月29日周一 凌晨3:26收件人： deeptools/pyGenomeTracks ***@***.***>抄送： Durian ***@***.***>, Author ***@***.***>主    题： Re: [deeptools/pyGenomeTracks] change colors of line plot for bedgraph matrix (Issue #365)
Hi,
It is indeed unclear.
The colormap can only be set if you choose type = matrix. For the moment, you cannot choose the color for the type = line:
https://github.com/deeptools/pyGenomeTracks/blob/488a6d3f9e81c6ca1af9f90484445070ed9c7024/pygenometracks/tracks/BedGraphMatrixTrack.py#L120-L130
Each line is written in grey and the average is plot in the default color from matplotlib (blue).
How would you use the colormap? Each line a color from the colormap?
Thanks
