### ISSUE TITLE
what's wrong with my dekker Hi-C matrix 

### ISSUE THREAD

**Issue by crazyhottommy** [deeptools/pyGenomeTracks#39]
Hi,
Using the testing data `Li_et_al.h5` in the repo worked fine.
However, for an in-house generated Hi-C matrix, I got some errors.

The format is dekker, and I converted it to h5 using `hicExport`.
I think my matrix format may not compatible with hicExport?

```bash
hicExport --inFile HiCMDA-WM115-R1__hg19__chr1__C-40000-iced.matrix.gz --outFileName WM115-R1_chr1 --inputFormat dekker --outputFormat h5

pyGenomeTracks  --tracks hic_chr1.ini -o hic_track.pdf --region chr1:106,731,614-117,436,036
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:2.0906879901885986
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 2.1874365565931537. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [x-axis]
INFO:pygenometracks.tracksClass:plotting 2. [spacer]
INFO:pygenometracks.tracksClass:plotting 3. [WM115-R1_chr1]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 3. [WM115-R1_chr1] to: 0.01, 3.0

/Users/mtang1/anaconda/envs/pgt/lib/python3.6/site-packages/matplotlib/colors.py:1012: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0

```
hic.ini

```

[x-axis]
#optional
#fontsize=20
# default is bottom meaning below the axis line
# where=top

[spacer]
# height of space in cm (optional)
height = 0.5

[WM115-R1]
file=WM115-R1_chr1.h5

title = WM115-R1_chr1
# The different options for color maps can be found here: https://matplotlib.org/users/colormaps.html
# the default color map is RdYlBu_r (_r) stands for reverse
colormap = RdYlBu_r
# depth is the maximum distance that should be plotted.
depth = 100000
# height of track (in cm) can be given. Otherwise, the height is computed such that the proportions of the
# hic matrix are kept (e.g. the image does not appear shrink or extended)
# height = 10
# min_value and max_value refer to the contacts in the matrix.
min_value = 0.1
max_value = 5

# the matrix can be transformed using the log1 (or log, but zeros could be problematic)
transform = log1p
# show masked bins plots as white lines
# those bins that were not used during the correction
# the default is to extend neighboring bins to
# obtain an aesthetically pleasant output
show_masked_bins = no
# if the track wants to be plotted upside-down:
# orientation = inverted
# optional if the values in the matrix need to be scaled the
# following parameter can be used. This is useful to plot multiple hic-matrices on the same scale
# scale factor = 1
file_type = hic_matrix
```
Some errors with the values. I noticed that in my matrix, there are nan. Is this a problem?
attached is the 40kb resolution contact matrix for chr1:
[HiCMDA-WM115-R1__hg19__chr1__C-40000-iced.matrix.gz](https://github.com/deeptools/pyGenomeTracks/files/2236849/HiCMDA-WM115-R1__hg19__chr1__C-40000-iced.matrix.gz)

How to best set the min_value and max_value?  what transformation should be used? some values are 0, log transform will cause problems?

Thanks,
Tommy

**Comment by fidelram** [comment]
What I see is a warning but not an error. Do don't get any  image?

**Comment by crazyhottommy** [comment]
It depends on the region to plot, sometimes it is an error. In this case, it just warning, I got a figure but only with one domain and no color gradient. I guess the resolution/quality of my data is bad. I attached the contact matrix before.

For a given matrix, do you first check the range of the values, and then choose the reasonable mix and max values?

Thanks,
Tommy

**Comment by fidelram** [comment]
usually the min and max default values are quite good. Unless I want consistent color scales between multiple plots I may not change the defaults. 

However, if you are facing this problem, it may be that your original hic matrix has some extreme values. This is usually caused by correcting algorithm when the matrix is not properly filtered and contains too many low values.

**Comment by crazyhottommy** [comment]
Thanks for your helpful insight. I will use some public high-quality data instead. Do you happen to have some high-resolution Hi-C h5 files that I can download? The files https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE63525  there are not normalized.
