### ISSUE TITLE
add border to tracks

### ISSUE THREAD

**Issue by Zepeng-Mu** [deeptools/pyGenomeTracks#398]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [x] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [ ] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
  - [x] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

  - [x] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

Hello,
I'm wondering if it's possible to add a border to the tracks. For example, when plotting bigwig tracks with `type=line` there is no x-axis, so the baseline is empty. It would be great if it's possible to add an x-axis or a black border around the track.

Thanks so much!

**Comment by lldelisle** [comment]
Hi,
We have a track which display horizontal lines (see https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/master_hlines.png and https://pygenometracks.readthedocs.io/en/latest/content/tracks/hlines.html). Would it solve your issue? We also have an option to display a grid on the y-axis with `grid = true`.

**Comment by lldelisle** [comment]
You are welcome.
