### ISSUE TITLE
Difficulties to import pygenometracks for python scripting usage

### ISSUE THREAD

**Issue by sebgra** [deeptools/pyGenomeTracks#400]
Hello !

I tried to work with pygenometracks  through python scripts. I used  : 
`from pygenometracks import tracks
`

to import the library in a conda env with : 
` _pygenometracks            3.0                        py_0    bioconda_`

Nevertheless I am stuck in importing the library and I got ModuleImportError : No module named 'pygenometracks'.

I also tried the camel case typing for import the library but it's the same. 

Any solution ? 

Thanks in advance

**Comment by lldelisle** [comment]
Hi,
Thanks for your interest in pyGenomeTracks.
I propose you to work with a fresh conda environment with the last version:
```bash
conda create -n pgt_3.7 pygenometracks=3.7
conda activate pgt_3.7
```
Then, you should be able to import the module:
```python

import matplotlib as mpl
mpl.use('agg')
import pygenometracks.tracksClass
ini_file = 'bed_squares_overlay.ini'

trp = pygenometracks.tracksClass.PlotTracks(ini_file, dpi=150)

current_fig = trp.plot("test1.png", "X", 3000000, 33000000)
```

**Comment by sebgra** [comment]
Thanks for the quick answer. Refreshing the env seems to have fixed the problem. 
I am still struggling to import and plot bigwig tracks.

Any suggestion ?
