### ISSUE TITLE
PyGenomeTracks   image shows a problem

### ISSUE THREAD

**Issue by Zheng19w** [deeptools/pyGenomeTracks#401]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [ ] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [ ] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.

  - [ ] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the [code/documentation).

  - [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

Dear professors

[x-axis]
#optional
#fontsize = 20
# default is bottom meaning below the axis line
# where = top
[spacer]
# height of space in cm (optional)
height = 0.5
[scrofa-Hi-C-muscle.10000]
file = scrofa-Hi-C-muscle.10000.cool
title = scrofa-Hi-C-muscle.10000
depth = 50000
# height = 10
#min_value =2.8
#max_value = 3.0
transform = log
show_masked_bins = false
file_type = hic_matrix              

Picture display is abnormal, how to solve this problem

![PGTplot (13)](https://user-images.githubusercontent.com/106860091/172051294-4ac8b95b-8860-4165-a88b-611cf6faeee1.png)

**Comment by Zheng19w** [comment]
I want to get picture 
![PGTplot (8)](https://user-images.githubusercontent.com/106860091/172051375-328f004d-6544-4a2a-8fd1-da1af7270bd4.png)
like this

**Comment by Zheng19w** [comment]
Then, I have convert muscle_40000_iced.matrix to h5

hicConvertFormat -m /public/home/zheng1996/Hic/hicpro/hic_results/matrix/muscle/iced/40000/muscle_40000_iced.matrix --bedFileHicpro /public/home/zheng1996/Hic/hicpro/hic_results/matrix/muscle/raw/40000/muscle_40000_abs.bed --inputFormat hicpro --outputFormat h5 -o 40000_iced.h5

-rw-rw-r-- 1 zheng1996 zheng1996 680M Jun  5 21:08 40000_iced.h5

height = 0.5
[40000_iced]
file = 40000_iced.h5
depth = 200000
transform = log1p
show_masked_bins = false
file_type = hic_matrix

/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/huawei/bin/pyGenomeTracks --tracks PGTplot.ini --region chrX:300000-350000  -o PGTplot.png --dpi 300

![PGTplot (19)](https://user-images.githubusercontent.com/106860091/172054618-8ec48c38-8e3a-41be-b9fe-4cef1a126492.png)

**Comment by Zheng19w** [comment]
I don't know how to solve this problem, I really want to use your tool

**Comment by lldelisle** [comment]
Hi,
I think you are missing a 0:
`depth = 200000 `-> 2000000
`pyGenomeTracks --tracks PGTplot.ini --region chrX:300000-350000 -o PGTplot.png --dpi 300` -> chrX:3000000-3500000

**Comment by lldelisle** [comment]
Also, it looks like you are using an old version.
You should do (once your environment is activated): `conda install pygenometracks=3.7`

**Comment by Zheng19w** [comment]
thank you very much!
I will try it immediately!



---- Replied Message ----
| From | Lucille ***@***.***> |
| Date | 06/05/2022 23:11 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [deeptools/pyGenomeTracks] PyGenomeTracks image shows a problem (Issue #401) |

Also, it looks like you are using an old version.
You should do (once your environment is activated): conda install pygenometracks=3.7

**Comment by Zheng19w** [comment]
I have tried to upgrade to version 3.7 and add 0, but still have no good results
![PGTplot (1)](https://user-images.githubusercontent.com/106860091/172061489-6be5416d-5400-4741-a4c5-5b1627e4bb14.png)

**Comment by Zheng19w** [comment]
Here are my COOL and H5 files









At 2022-06-05 23:11:26, "Lucille Delisle" ***@***.***> wrote:

Also, it looks like you are using an old version.
You should do (once your environment is activated): conda install pygenometracks=3.7

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| coolandh5.zip |
| |
| (812.1M, 2022年6月21日 1:03 到期) |
| |
| 下载 |
| |
| |

**Comment by lldelisle** [comment]
Hi,
I am afraid the problem is not pgt but your cool file. I am back to work on Tuesday, please send me your cool file by email at Lucille.delisle@epfl.ch I will check during the week.

**Comment by Zheng19w** [comment]
Dear professor:
                     Thank you very much !  my cool file  is good  PGT is a very useful tool 
                      chrX:300000000-350000000     this problem can be solved 
![PGTplot (25)](https://user-images.githubusercontent.com/106860091/172087009-ab592929-f5d3-4e2e-89fb-9e76f66fde10.png)

**Comment by Zheng19w** [comment]
But I am not sure how to adju
![hic_track](https://user-images.githubusercontent.com/106860091/172114726-3e91a593-c7e2-4660-9ee5-96794db1b925.png)
st the Y-axis, why only 0 to 2 is displayed. The figure below is 0 to 200, how to solve this problem

**Comment by lldelisle** [comment]
You can use `min_value`, `max_value` but I think your scale is the good one. You can also play with `transform = no` instead of log1p.

**Comment by Zheng19w** [comment]
Thank you for your patience @lldelisle
