### ISSUE TITLE
gene symbol

### ISSUE THREAD

**Issue by BioEpi** [deeptools/pyGenomeTracks#415]
Hello,
     I was just wondering whether pyGenomeTracks can automatically load Genecode GTF. As it is very very slowly to load the custome GTF.

**Comment by lldelisle** [comment]
Hi @BioEpi 
Could you tell me which version of pyGenomeTracks you are using? Which is the command line you launched? And which gtf you are trying to load? For me it is not so slow to plot a GTF.

**Comment by BioEpi** [comment]
Hello, 
I try to convert the GTF to bed, and run pyGenomeTracks. However, I got this error:

Traceback (most recent call last):
  File "/data/anaconda3/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/data/anaconda3/lib/python3.8/site-packages/pygenometracks/plotTracks.py", line 279, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height, fontsize=args.fontSize, dpi=args.dpi, track_label_width=args.trackLabelFraction)
  File "/data/anaconda3/lib/python3.8/site-packages/pygenometracks/tracksClass.py", line 111, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/data/anaconda3/lib/python3.8/site-packages/pygenometracks/tracks/BedTrack.py", line 171, in __init__
    self.interval_tree, min_score, max_score = self.process_bed()
  File "/data/anaconda3/lib/python3.8/site-packages/pygenometracks/tracks/BedTrack.py", line 232, in process_bed
    if bed.score < min_score:
TypeError: '<' not supported between instances of 'str' and 'float'


here is my bed file:
chr1    65418   71584   ENSG00000186092.7       OR4F5   +
chr1    450739  451677  ENSG00000284733.2       OR4F29  -
chr1    685678  686672  ENSG00000284662.1       OR4F16  -
chr1    923922  944574  ENSG00000187634.13      SAMD11  +
chr1    944202  959308  ENSG00000188976.11      NOC2L   -
chr1    960583  965718  ENSG00000187961.14      KLHL17  +
chr1    966481  975864  ENSG00000187583.11      PLEKHN1 +

**Comment by BioEpi** [comment]
> Hi @BioEpi Could you tell me which version of pyGenomeTracks you are using? Which is the command line you launched? And which gtf you are trying to load? For me it is not so slow to plot a GTF.

hello, here is the command I used: pyGenomeTracks --tracks tracks_TAD_plot.ini -o out.pdf --region chr1:10000-20000

**Comment by lldelisle** [comment]
Do you have bedtools installed?
For me it took 3 seconds:
```
(pgt_3.7) [ldelisle@SV-49-002 Downloads]$ cat test.ini 
[gtf]
file = hg38.knownGene.gtf.gz

(pgt_3.7) [ldelisle@SV-49-002 Downloads]$ time pgt --tracks test.ini --region chr1:10000-20000 -o out.pdf
WARNING:pygenometracks.tracksClass:title not set for section 1. [gtf]

INFO:pygenometracks.tracksClass:initialize 1. [gtf]
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 2665.40it/s]
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:2.320542335510254
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 0.5319148936170213. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [gtf]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 5.68,-0.08

real    0m3.483s
user    0m3.408s
sys     0m0.655s

```

**Comment by BioEpi** [comment]
sorry. I have updated the version, and now everything is ok
