### ISSUE TITLE
how to highlight a region

### ISSUE THREAD

**Issue by BenxiaHu** [deeptools/pyGenomeTracks#416]
Hello,
   How to highlight a region (e.g., chr1:10000-20000)?

<img width="637" alt="image" src="https://user-images.githubusercontent.com/12387462/193354558-05a5bee4-49d3-4ece-9d02-00ca1e577100.png">

**Comment by lldelisle** [comment]
Like this?
https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/master_vhighlight.png
You can use `vhighlight`:
https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/vhighlight.ini

**Comment by lldelisle** [comment]
I close the issue but feel free to reopen it if needed.
