### ISSUE TITLE
colormap definition 

### ISSUE THREAD

**Issue by BenxiaHu** [deeptools/pyGenomeTracks#417]
Hello,
   would you like to explain the colormap:
colormap = ['white', (1, 0.88, .66), (1, 0.74, 0.25), (1, 0.5, 0), (1, 0.19, 0), (0.74, 0, 0), (0.35, 0, 0)] (https://pygenometracks.readthedocs.io/en/latest/content/examples.html)

<img width="707" alt="image" src="https://user-images.githubusercontent.com/12387462/193496857-4efdc25f-d79e-49db-a259-cbc03bafe3c3.png">

this triangle heatmap looks great. I just want to know how to set the color.

**Comment by lldelisle** [comment]
Hi,
There are 2 ways to define a colormap in the configuration file:

1. Either you use an existing colormap from matplotlib available at https://matplotlib.org/stable/tutorials/colors/colormaps.html
2. Or you manually define the different colors that form the colormap and you put them between `[]` separated by `,`.

Same, to define a color you have 3 choices:

1. choose a named color from matplotlib: https://matplotlib.org/stable/gallery/color/named_colors.html
2. you use the hexa code for the color, for example `'#0000ff` for blue
3. you use the rgb where each value is between 0 and 1, for example `(1, 0.88, .66)`.

So `['white', (1, 0.88, .66), (1, 0.74, 0.25), (1, 0.5, 0), (1, 0.19, 0), (0.74, 0, 0), (0.35, 0, 0)] ` is a custom colormap going from white to brown through different yellow/orange.

The different ways to define colormaps are in the documentation (https://pygenometracks.readthedocs.io/en/latest/content/tracks/hic_matrix.html#output-of-make-tracks-file):
```
# The different options for color maps can be found here:
# https://matplotlib.org/users/colormaps.html
# the default color map is RdYlBu_r (_r) stands for reverse
# If you want your own colormap you can put the values of the color you want
# For example, colormap = ['blue', 'yellow', 'red']
# or colormap = ['white', (1, 0.88, .66), (1, 0.74, 0.25), (1, 0.5, 0), (1, 0.19, 0), (0.74, 0, 0), (0.35, 0, 0)]
```

**Comment by lldelisle** [comment]
I close the issue but feel free to reopen if needed.
