### ISSUE TITLE
how does pyGenomeTracks plot compartment

### ISSUE THREAD

**Issue by BenxiaHu** [deeptools/pyGenomeTracks#418]
Hello,
   I was just wondering whether pyGenomeTracks can plot compartments based on Hi-C contact matrix?
Best,

**Comment by lldelisle** [comment]
Hi,
You can calculate compartments with https://hicexplorer.readthedocs.io/en/latest/content/tools/hicPCA.html then you can display the bedgraphs with pyGenomeTracks.
pyGenomeTracks does not analyse your data, it just displays the results.

**Comment by BioEpi** [comment]
thanks. But what I want to ask is how to plot square heatmap (compartment), not the beagraph.

**Comment by lldelisle** [comment]
Sorry I misunderstood.
You have the `hic_matrix_square` (documentation: https://pygenometracks.readthedocs.io/en/latest/content/tracks/hic_matrix_square.html, example:  https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/master_hic_square.png). Is it what you want?

**Comment by BioEpi** [comment]
yes. that's what I want. what parameters I need to set to get that square heatmap?

**Comment by BioEpi** [comment]
gotcha. thanks. how to set the size of entire figure smaller. What I mean is to scale the figure.

**Comment by BioEpi** [comment]
I have another question, given that I have 3 bw files (for RNA-seq), How do I set the same scale for these bigwig files?

**Comment by lldelisle** [comment]
1. For the figure, you can play with `--width`, see https://pygenometracks.readthedocs.io/en/latest/content/usage.html#pygenometracks
2. Duplicated with #321, short answer, for the moment we cannot do it in pyGenomeTracks.

**Comment by lldelisle** [comment]
I close the issue but feel free to reopen if needed.
