### ISSUE TITLE
Links bug with use_middle

### ISSUE THREAD

**Issue by Jeff1995** [deeptools/pyGenomeTracks#422]
Hi developers! Thanks for developing this great tool. I have been using pyGenomeTracks to visualize links file with "use_middle" mode in a [package](https://github.com/gao-lab/GLUE) I developed. However, it occasionally raises error like this: gao-lab/GLUE#52.

I have looked into the error and spotted the reason.

When the linked regions [start1, end1] encompasses [start2, end2], there can be situations where:

* start1 < start2
* end1 >> end2

In which case we can have mid1 > mid2, producing a null interval in the following line:

https://github.com/deeptools/pyGenomeTracks/blob/2085e04a4bdea7690b52618d5dbe62410376992c/pygenometracks/tracks/LinksTrack.py#L502

**Comment by Jeff1995** [comment]
I have made the above PR to fix this. Could you review it and see if that's the way to go?

**Comment by lldelisle** [comment]
Hi,
Thank you very much, yes perfect.
