### ISSUE TITLE
white stripes in hic matrix

### ISSUE THREAD

**Issue by Mava04** [deeptools/pyGenomeTracks#431]
Hi,

I am trying to display TADs at different resolution (1-2-3 kb) from a capture-Hi-C experiment, and I have many white stripes in my plots despite setting the option show_masked_bins = false. I tried using both cool and h5 files as the input, and the output is the same.
Here is a sample image:
[tad_image.pdf](https://github.com/deeptools/pyGenomeTracks/files/10285228/tad_image.pdf)

My configuration file is:
[x-axis]
where = top

[hic matrix]
file = {path_to_input_file}
file_type = hic_matrix
title = Title
depth = 400000
colormap = YlOrBr
min_value = 1.0
max_value = 30
transform = log1p
width = 9.0
scale factor = 1.0
show_masked_bins = false

and the command is:

pyGenomeTracks --tracks config.ini --region chr3L:10950000-11900000 -o tad_image.pdf

Moreover, I get a warning that the bin size is not homogeneous, despite the fact that it should be.

I am using pyGenomeTracks version 3.6 and python version 3.7.13 .

Why are those bins not removed? How could I pre-process the data to avoid the white stripes?

Thank you in advance

**Comment by cgirardot** [comment]
Hi @lldelisle 
let me comment on the processing. I am using hicexplorer (3.7.2):
- The raw matrix is obtained with hicBuildMatrix
- inter-chr contacts removed with hicAdjustMatrix -a keep --interIntraHandling inter
- signal scaling with hicNormalize --normalize multiplicative -mv ${RATIO}

no balancing. 
thx

**Comment by lldelisle** [comment]
Hi @Mava04,
Sorry for the late reply. pyGenomeTracks only display the data. The option `show_masked_bins = false`, only works if the input matrix has 'masked bins'. This happens during the correction process. If you matrix is not corrected then it is normal that you don't have masked bins. 
For the warning about the bin size, it is probably that the chromosome does not have a size which is a multiple of the bin size, therefore, the last bin is smaller.
I hope this answer your questions.

**Comment by cgirardot** [comment]
@lldelisle that makes sense, thank you. The data is captureHiC and the matrix basically  has signal only for 2 regions; I am not sure how the matrix balancing correction will perform. Do you have experience with this kind of data?

**Comment by lldelisle** [comment]
If they are 'region capture' data, you can do balancing. I do region capture data with a single region of 5Mb and it works very well.

**Comment by cgirardot** [comment]
with the usual Imakaev algo? Thx again

**Comment by lldelisle** [comment]
I think you can use KR correction or ICE, both should work.
