### ISSUE TITLE
How to get annotation for mm10

### ISSUE THREAD

**Issue by TakatoG** [deeptools/pyGenomeTracks#432]
Hi 
I made HiC map from HiCexplorer and I want to make TADs plots from pygenomeTracks.
I wonder how to make annotation like H3K27me3 for mm10.
I got a TADsplots but I want to make additional annotation for mm10.
Could you tell me how to make annotation files for mm10??

**Comment by lldelisle** [comment]
Hi,
Histone mark profiles like H3K27me3 highly depends on the cell type (cell line, tissue etc...). You can find some profiles in bigwig formats on [ENCODE](https://www.encodeproject.org/search/?type=File&file_format=bigWig&target.label=H3K27me3&assembly=mm10&assembly=mm10-minimal).

**Comment by TakatoG** [comment]
Thank you for your information!
Really appreciate.
I also want to get mm10 gene annotation.(such like dm3 genes) How can I get it??

**Comment by lldelisle** [comment]
You can get gtf from different places: [Ensembl](http://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/Mus_musculus.GRCm38.102.gtf.gz) provides very comprehensive set of annotations, [Gencode](https://www.gencodegenes.org/mouse/release_M25.html) provides multiple gtf with different filtered set of annotations or [UCSC](https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/genes/).

**Comment by TakatoG** [comment]
Hi, lldelisle.
Thank you for your information !
Really appreciate.
