### ISSUE TITLE
.h5 to .arcs

### ISSUE THREAD

**Issue by TakatoG** [deeptools/pyGenomeTracks#433]
Hi!
I use pcHiC data and I want to get promotor-enhancer interaction. I got .h5 format from HiCExplorer of it. Do you know how to change this file format to .arcs or how can I generate .arc files??
Can .arcs file load to igv or other genome browser?

**Comment by lldelisle** [comment]
Hi,
promoter capture Hi-C generates a profile for each promoter. Do you want to display as arc any interaction or just the significant ones?
`.arcs` are also `.bedpe` so I think they can be loaded into igv.

**Comment by TakatoG** [comment]
Hi, thank you for reply.
I want to generate .arc files. Do you know any software (such like HiCExplorer) to generate .arc files?

**Comment by lldelisle** [comment]
You can convert your matrix to cool with HiCExplorer [hicConvertFormat](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html) and then do:
```
cooler dump --join your_matrix.cool > all_interactions.arcs
```
The last column is the number of pairs supporting this interaction.
If you ant to put it in IGV, you need to slightly modify it:
```
awk -v OFS="\t" '{$6=$5;$5=NR;print}' all_interactions.arcs > all_interactions.bedpe
```

**Comment by TakatoG** [comment]
Thank you for your message.
Now I understand.

**Comment by lldelisle** [comment]
I close it but feel free to reopen if needed.
