### ISSUE TITLE
invalid [orientation=inverted] in [genes]？

### ISSUE THREAD

**Issue by hongweiyu97** [deeptools/pyGenomeTracks#434]
Hi!

I wrote this command [orientation=inverted] in the configuration file, but the final drawing of the gene did not reverse. 
I want the pile of genes to pile up (not down). 

pyGenomeTracks 3.7

[genes]
file = genes.bed
...
orientation=inverted

**Comment by lldelisle** [comment]
Hi,
Would you mind to show what you get and draw what you were expected with `orientation = inverted`?

**Comment by hongweiyu97** [comment]
> Hi, Would you mind to show what you get and draw what you were expected with `orientation = inverted`?

Thank you for your prompt reply！
Whether I add [orientation=inverted] or not, I end up with genes that pile down. My goal is to stack genes up.

<img width="290" alt="1" src="https://user-images.githubusercontent.com/104889391/213212096-ed24cebd-6615-4f8b-ac4c-477dff1a1316.png">

**Comment by lldelisle** [comment]
Indeed we did not implemented it for the display 'interleaved', nor 'stacked'... This is easy to do. I will write a PR.

**Comment by lldelisle** [comment]
This has been solved in the new release 3.8 which will be on coda later today.
