### ISSUE TITLE
flip strand orientation

### ISSUE THREAD

**Issue by mtinti** [deeptools/pyGenomeTracks#444]
Hi, 
Is it possible to flip the strand orientation so that genes/tracks on the minus strand are plotted from 5' to 3'?
I have been looking for a while at the manual but couldn't find an option.

Also, thanks for this great tool!
Michele

**Comment by lldelisle** [comment]
Hi,
Would `--decreasingXAxis` in https://pygenometracks.readthedocs.io/en/latest/content/usage.html#id4 be what you are looking for?
If not could you make a schema of what you would like?
