### ISSUE TITLE
Gene track causes misalignment by either showing entire or no gene

### ISSUE THREAD

**Issue by jmschrei** [deeptools/pyGenomeTracks#445]
I've been trying to add a gene track subplot to some other subplots in a Jupyter notebook and have found that it produces an incorrect alignment between the gene track and other plots because, even when a region is given, either the entire gene or no gene at all are displayed, and the plot always begins with the first found gene in the region, not at the provided coordinates.

Here is the code I'm using. Note that the second plot should be shifted over by 5,000bp compared to the first plot.

```python
plt.figure(figsize=(12, 2))

ax = plt.subplot(211)
track_config  = dict(file=gtf_path, 
                     prefered_name="gene_name",
                     style='UCSC',
                     merge_transcripts=True, 
                     global_max_row=False, 
                     region=[(chrom, start, end)])
track = pygtk.GtfTrack(track_config)
track.plot(ax, chrom, start, end)
plt.axis('off')

ax = plt.subplot(212)
track_config  = dict(file=gtf_path, 
                     prefered_name="gene_name",
                     style='UCSC',
                     merge_transcripts=True, 
                     global_max_row=False, 
                     region=[(chrom, start+5000, end)])
track = pygtk.GtfTrack(track_config)
track.plot(ax, chrom, start+5000, end)
plt.axis('off')

plt.tight_layout()
plt.show()
```

And here is the output, which looks identical.

![image](https://user-images.githubusercontent.com/3916816/236697284-92a1f2ff-2981-49c7-85c5-d7c287ffa529.png)

If I shift over by 9000bp to just barely remove CLEC4C, I'd expect there to be whitespace before NANOGNB. Instead, NANOGNB just snaps to the left side. 

![image](https://user-images.githubusercontent.com/3916816/236697376-97c05e76-03b5-4105-962d-5798774c62a8.png)

So.. it looks like I can't align multiple subplots on the same x-axis because there's no guarantee that the provided regions correspond to the actual gene track output in the image. Is this correct in the command-line tool, or is it possible that all gene tracks suffer from this issue?

**Comment by lldelisle** [comment]
I will have a look this afternoon.

**Comment by lldelisle** [comment]
I think you just need to set the x_axis limits after each plot like we do here: https://github.com/deeptools/pyGenomeTracks/blob/b8918d43b0bd1ca9dd2939fdd0d93a5a297d0453/pygenometracks/tracksClass.py#L530-L533
In your case:
```
plt.figure(figsize=(12, 2))

ax = plt.subplot(211)
track_config  = dict(file=gtf_path, 
                     prefered_name="gene_name",
                     style='UCSC',
                     merge_transcripts=True, 
                     global_max_row=False, 
                     region=[(chrom, start, end)])
track = pygtk.GtfTrack(track_config)
track.plot(ax, chrom, start, end)
ax.set_xlim(start, end)
plt.axis('off')

ax = plt.subplot(212)
track_config  = dict(file=gtf_path, 
                     prefered_name="gene_name",
                     style='UCSC',
                     merge_transcripts=True, 
                     global_max_row=False, 
                     region=[(chrom, start+5000, end)])
track = pygtk.GtfTrack(track_config)
track.plot(ax, chrom, start+5000, end)
ax.set_xlim(start + 5000, end)
plt.axis('off')

plt.tight_layout()
plt.show()
```

**Comment by jmschrei** [comment]
Thanks for looking into it. Is it possible to add documentation for this somewhere or potentially an example of loading a gene track into one subplot and a signal track from a bw (or some other source) into another subplot and have them align?

**Comment by lldelisle** [comment]
The reason why we are not documenting the 'API' of pygenometracks is because for the moment it is not stable. We would like to support API in version 4.0 and document it. Unfortunately, we are running out of resources to develop it. But this is still our project. See #20
