### ISSUE TITLE
label of bed file

### ISSUE THREAD

**Issue by Simple53** [deeptools/pyGenomeTracks#446]
I have a bed file containing IDs. How can I plot these regions and display their names at the center inside or below each region?
![a](https://user-images.githubusercontent.com/74480804/236759128-63d3ba4f-81e6-420f-aeed-fd42ab3578e6.png)

**Comment by lldelisle** [comment]
Hi,
Unfortunately this is for the moment not possible but there is a trick that I use for that. You create another bed with the same labels but where you modify the coordinates:
```bash
original_bed=my.bed
awk -v OFS="\t" -v shift=10000 '{middle=($2 + $3) / 2; $2 = int(middle - shift); $3=$2 + 1;print}' ${original_bed} > ${original_bed/.bed/_middle.bed}
```
Then when you create your ini file:
```bash
echo "[my bed]
file = $original_bed
labels = false

[my labels]
file = ${original_bed/.bed/_middle.bed}
color = none
border_color = none
color_utr = none
labels = true
" > test.ini
```

**Comment by Simple53** [comment]
Thanks! The trick works.
