### ISSUE TITLE
bigwig plot wrong

### ISSUE THREAD

**Issue by jphe** [deeptools/pyGenomeTracks#45]
HI, I use pyGenomeTracks to draw igv plot for bigwig files, but I met a problem for the output plot, some of them seems wrong , it has many blank and fake signals, attached is two examples. I have checked the bigwig file in igv, the bigwig file are correct, why?  Thanks.
[test1.pdf](https://github.com/deeptools/pyGenomeTracks/files/2481671/test1.pdf)
[test2.pdf](https://github.com/deeptools/pyGenomeTracks/files/2481672/test2.pdf)

**Comment by fidelram** [comment]
This may be  caused by a code to plot negative values of a different color. Can you install this commit of pyGenomeTracks: 7bf1c0292a2b9de412d903edde594e0cea49af5e ?

Here is some information on how to do that: https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

**Comment by jphe** [comment]
Yes, it's fixed, thanks.

pip install --upgrade  git+git://github.com/deeptools/pyGenomeTracks.git@7bf1c0292a2b9de412d903edde594e0cea49af5e#diff-9b07ceac7960ac7e6ec176f506e3e9cf
