### ISSUE TITLE
Bigwig display at base pair zoom level

### ISSUE THREAD

**Issue by antunderwood** [deeptools/pyGenomeTracks#452]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [x] Search whether this issue (or a similar issue) has been solved before
No similar issues
  - [x ] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
3.8
  - [x] Paste the full pyGenomeTracks command that produces the issue below
pyGenomeTracks --tracks bigwig_track.ini --region X:2,601,100-2,601,200 -o bigwig.png

  - [x] Paste the output printed on screen from the command that produces the issue
WARNING:pygenometracks.tracksClass:title not set for section 2. [sequence]

INFO:pygenometracks.tracksClass:initialize 1. [bigwig file test]
INFO:pygenometracks.tracksClass:initialize 2. [sequence]
INFO:pygenometracks.tracksClass:initialize 3. [x-axis]
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:0.12220454216003418
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 6.781914893617022. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [bigwig file test]
INFO:pygenometracks.tracksClass:plotting 2. [sequence]
INFO:pygenometracks.tracksClass:plotting 3. [x-axis]

I used the following ini file 
```
[bigwig file test]
file = bigwig.bw
# height of the track in cm (optional value)
height = 4
title = breaks
min_value = 0
max_value = 5
alpha = 1
# type = line:5
type = fill
summary_method = mean
number_of_bins = 300
file_type = bigwig
[sequence]
file = /shared/home/anthony/s3-mounts/accessory_files/bwa_indices/hg19/refseq/hg19.fasta
file_type = fasta
[x-axis]
```
I want to display bigwig files at base zoom level along with the sequence.
However the bars appear faint at this zoom level. Can you suggest an alternative format or command so that I can have a bar per base. Thanks

![image](https://github.com/deeptools/pyGenomeTracks/assets/423/8d03fdd4-f1ed-4f52-80b7-7d0ee8c5ad96)

**Comment by lldelisle** [comment]
Hi,
I think there are 2 options:
1. Use the same number of bins as the number of bases.
2. Convert your bigwig to bedgraph so you can see a 'barplot'.
The output will be different so I suggest you to test both. If you need help for one or the other, tell me.

**Comment by antunderwood** [comment]
Many thanks for the quick reply.
If I have this ini
```
[bigwig file test]
file = bigwig.bw
# height of the track in cm (optional value)
height = 4
title = breaks
min_value = 0
max_value = 5
alpha = 1
number_of_bins = 100
file_type = bigwig
[sequence]
file = /shared/home/anthony/s3-mounts/accessory_files/bwa_indices/hg19/refseq/hg19.fasta
file_type = fasta
[x-axis]
```
with this command `pyGenomeTracks --tracks bigwig_track.ini --region X:2,601,100-2,601,199 -o bigwig.png`

I get this which is better but does not show histograms
![image](https://github.com/deeptools/pyGenomeTracks/assets/423/7c1c4983-ce77-46a4-b086-d8dbf2d8c235)

Using a bedgraph format (I dodn't know you could index them with tabix before!). I can get a nice output. Thanks
![image](https://github.com/deeptools/pyGenomeTracks/assets/423/ea0c6bc4-c974-443d-84d0-76608670014c)

**Comment by antunderwood** [comment]
A quick Q - is it possible to call the functions from within other python code using imports?
