### ISSUE TITLE
gappedPeak not working

### ISSUE THREAD

**Issue by NMaziak** [deeptools/pyGenomeTracks#462]
Hello, 

Thanks for providing a wonderful tool! I have pyGenomeTracks version 3.8. I have a gappedPeak file, the first two lines look like this: 

```
chrY    887530  917120  Peak_7  .       .       887570  887820  255,0,0 3       1,250,1 0,40,29589      294.0   -1      -1
chrY    925470  955780  Peak_12 .       .       931520  933260  255,0,0 3       1,1740,1        0,6050,30309    77.0    -1      -1
```

However, when I plot it, it comes out looking like a normal peak, in the .ini file, I have the following: 
```
[HMMRATAC]
file = ATAC_bw/sample_peaks.gappedPeak
file_type = bed
```

Would you happen to know why it won't work? 

Any help is greatly appreciated. 

Best,
Noura
![ATAC2](https://github.com/deeptools/pyGenomeTracks/assets/61707029/294de7d7-37a8-45e2-ae2e-453386c7b7e9)

**Comment by lldelisle** [comment]
Hi,
Do you have tabulations in your file?
Do you have an error message?
Thanks,
Lucille

**Comment by lldelisle** [comment]
I will have a closer look tomorrow.

**Comment by lldelisle** [comment]
It seems that your 'gappedPeak' does not follow exactly the format described by UCSC:
https://genome.ucsc.edu/FAQ/FAQformat.html#format14
And this is what pyGenomeTracks gives as message:
```
Warning: The block field 5 (score) is not valid: ..
Error message: could not convert string to float: '.'
Only the first 4 fields will be used.
```
There are 2 ways to convert your gappedPeak file to a 'conform' gappedPeak file:
- With awk:
`awk -v OFS="\t" '{$5=0;print}' input.gappedPeak > fixed.gappedPeak`
- With sed:
`sed 's/\.\t\./0\t./' input.gappedPeak > fixed.gappedPeak`

Here is the result:
![test](https://github.com/deeptools/pyGenomeTracks/assets/30404086/c1d0ca24-b283-4a7c-9d1b-f35f4098fff0)

Feel free to reopen the issue if the error is still here.

**Comment by NMaziak** [comment]
Hi Lucille, thank you so much for the prompt reply. I didn't catch the warning, very sorry about that. Will fix it!
