### ISSUE TITLE
Flipping the reverse strand genes

### ISSUE THREAD

**Issue by Snehal1894** [deeptools/pyGenomeTracks#463]
Hello,
I couldn't find any option to reverse the orientation of genes.
I want to reverse the tracks of 3'-5' gene , i'e plot these genes in 5'-3'

**Comment by lldelisle** [comment]
Hi,
Do you want to plot, let say from chr2:75'000'000 on left to chr2:'74'000'000 on right?
In this case you need to use `--decreasingXAxis1  see [Usage](https://pygenometracks.readthedocs.io/en/latest/content/usage.html#pygenometracks).

If it is something else, can you be more explicit, please?

**Comment by Snehal1894** [comment]
Yes I was able to do it using --decreasingXAxis. Thank you for prompt response :)
