### ISSUE TITLE
Unable to install with conda phyton 3.9

### ISSUE THREAD

**Issue by diegohernansanchez** [deeptools/pyGenomeTracks#476]
Hi,
Im running Anaconda in Windows, with conda version 23.5.0 and python version 3.9.18, and when trying the command line for installing pygenometracks it is unsucessfull:

+++
(base) PS C:\Users\diegosanchez> conda create -n pygenometracks_test -c bioconda -c conda-forge mamba python=3.9
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 23.5.0
  latest version: 24.5.0

Please update conda by running
    $ conda update -n base -c defaults conda
Or to minimize the number of packages updated during conda update use
     conda install conda=24.5.0

## Package Plan ##
  environment location: C:\Users\diegosanchez\anaconda3\envs\pygenometracks_test
  added / updated specs:
    - mamba
    - python=3.9
  
... etc., all packages intalled OK...

(base) PS C:\Users\diegosanchez> conda activate pygenometracks_test
(pygenometracks_test) PS C:\Users\diegosanchez> mamba install -c conda-forge -c bioconda pygenometracks

Looking for: ['pygenometracks']

bioconda/win-64 (check zst)                         Checked  0.3s
bioconda/noarch (check zst)                         Checked  0.2s
pkgs/main/win-64 (check zst)                       Checked  0.0s
pkgs/main/noarch (check zst)                        Checked  0.0s
pkgs/r/win-64 (check zst)                           Checked  0.0s
pkgs/r/noarch (check zst)                           Checked  0.0s
pkgs/msys2/win-64 (check zst)                       Checked  0.0s
pkgs/msys2/noarch (check zst)                       Checked  0.0s
bioconda/win-64                                    122.0 B @   1.2kB/s  0.1s
pkgs/msys2/win-64                                   35.1kB @  28.5kB/s  1.1s
pkgs/main/win-64                                     5.5MB @   3.9MB/s  1.4s
pkgs/r/win-64                                      633.1kB @ 363.1kB/s  0.3s
pkgs/msys2/noarch                                  103.0 B @  58.0 B/s  0.0s
pkgs/r/noarch                                        2.1MB @   1.1MB/s  0.6s
pkgs/main/noarch                                   712.7kB @ 345.7kB/s  0.3s
bioconda/noarch                                      5.2MB @   2.5MB/s  2.1s
conda-forge/noarch                                  14.7MB @   3.7MB/s  4.0s
conda-forge/win-64                                  22.1MB @   5.0MB/s  4.5s

Pinned packages:
  - python 3.9.*

Could not solve for environment specs
The following packages are incompatible
└─ pygenometracks is not installable because there are no viable options
   ├─ pygenometracks [2.1|3.0|...|3.3] would require
   │  └─ pybigwig >=0.3.4 , which does not exist (perhaps a missing channel);
   ├─ pygenometracks [3.3|3.4] would require
   │  └─ pybigwig >=0.3.16 , which does not exist (perhaps a missing channel);
   ├─ pygenometracks [3.5|3.5.1|3.6] would require
   │  └─ pybedtools >=0.8.1 , which does not exist (perhaps a missing channel);
   └─ pygenometracks [3.7|3.8|3.9] would require
      └─ bx-python >=0.8.13 , which does not exist (perhaps a missing channel).

Do you think it is possible that the warning  ==> WARNING: A newer version of conda exists. <== is related to this? I run the suggested:
$ conda update -n base -c defaults conda
but the it does not change version.

Thanks!
diego

**Comment by lldelisle** [comment]
Hi,
I am sorry but pygenometracks do not work on windows. I can only propose you to use WSL or use it on a galaxy server like usegalaxy.eu.
