### ISSUE TITLE
Visualize loop in hic matrix

### ISSUE THREAD

**Issue by yancychy** [deeptools/pyGenomeTracks#477]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [ ] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [ ] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
hicexplorer/3.7.2
Python 3.7.9

  - [ ] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

  - [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

Hi,  Can pyG visulize the loops like juicebox? Thank you.

**Comment by lldelisle** [comment]
Hi,
I am not sure I understand your question. pyGenomeTracks allows to display matrices and you can highlight 'loops' either by overlaying a square or by putting links below, like here:
![master_arcs_use_middle](https://github.com/deeptools/pyGenomeTracks/assets/30404086/f5fb0b8f-45dc-44be-929e-5acd06260c1d)
The ini file is:
https://github.com/deeptools/pyGenomeTracks/blob/master/pygenometracks/tests/test_data/arcs_use_middle.ini

**Comment by yancychy** [comment]
Thanks so much. It's the square loop on hic map. I thought only arc plot is visualized under the hic map in the example page https://pygenometracks.readthedocs.io/en/latest/content/examples.html.
