### ISSUE TITLE
TAD classification track

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/pyGenomeTracks#48]
Hi,

I am updating the test cases of HiCExplorer hicPlotTADs right now, and there is the track 'TAD classification'. With the usage of pyGenomeTracks it is just blue and does not show different kind of chromatin stages anymore. How can I bring this back? 

Thanks,

Joachim

**Comment by fidelram** [comment]
I am surprised that this does not work. I think that what was called TAD classification in hicexplorer has a different name. The trick is that the bed file has to have color values. Then the triangles are colored accordingly. 

Next week when I return I can take a look.

**Comment by lldelisle** [comment]
@joachimwolff do you still have issues with this track? Do you remember the test which was giving strange results?
Thanks,
