### ISSUE TITLE
Please update PyPi as it still provides only version 3.8

### ISSUE THREAD

**Issue by jan1034** [deeptools/pyGenomeTracks#481]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [x] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [x] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
pyGenomeTracks 3.8 Python 2.7.16 matplotlib 3.8

  - [ ] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

  - [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

Thank you for this nice tool. 
Unfortunately I am dependent on the PyPi installation and updated my enviroment to use matplotlib>=3.8. As the latest pyGenomeTracks is not available yet on PyPi and 3.8 is not working with matplotlib >=3.8, I would be really grateful if you could update pyGenomeTracks on PyPi as well. 

Bests Jan

**Comment by lldelisle** [comment]
Hi,
Sorry for the delay. It is now on pypi.
