### ISSUE TITLE
Bam file usage

### ISSUE THREAD

**Issue by santoshbiowarrior333** [deeptools/pyGenomeTracks#487]
Hi am looking for a way to use my modified bam file where i have likelihood of modification.
Is it possible to plot bam file?

Also a way to define the likelihood threshold so that i can colour those points with colour of my interest?

Thank you for this amazing good looking plot generator.

**Comment by lldelisle** [comment]
Hi,
I am sorry, this is something that has been asked by users a lot of times and we never managed to find the time to do it.
Best,
Lucille

**Comment by joachimwolff** [comment]
Maybe you can transform the bam to a bed and plot this?

Lucille Delisle ***@***.***> schrieb am Do. 19. Dez. 2024 um
17:24:

**Comment by santoshbiowarrior333** [comment]
Thank you, i am trying manual way as suggested above to have bed file. I am wondering in the 9th column, how can i assign colour, i tried R,G,B colours, then #colour_codes, but none of them automatically gets chosen. am i doing something odd here? I really appreciate your help here as i have many tracks that i wish to display and each track as 3 colurs.

**Comment by lldelisle** [comment]
Hi @santoshbiowarrior333,
Do you still need help for the colors?

**Comment by santoshbiowarrior333** [comment]
> Hi @santoshbiowarrior333, Do you still need help for the colors?

Hi, Thank you for your help, I found a way to edit the bam to txt and now i can do it manually as colour assigning, so covered for now. But would be great if your team could do something for bam files visualization, it would be amazing.
