### ISSUE TITLE
Moved user request from HiCExplorer

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/pyGenomeTracks#49]
Hello,
This tool is really great. It helps to save time with illustrator...
A possible bug:

It looks like for a bed file when you do not want to print the label, they are printed anyway.
I would add:
- [ ] the possibility to plot all annotations from a bed file on one row (even if the label overlap).

the possibility to plot the normalized count of the matrices (not only log transformed data).
the possibility to auto-width the matrices in order to have square bins (not diamond).
Many thanks,

Lucille

@lldelisle I moved your request because hicPlotTADs is developed as pyGenomeTracks now.

**Comment by lldelisle** [comment]
OK Thanks

**Comment by vivekbhr** [comment]
@lldelisle I agree the printing of labeling is not ideal as it's mostly influenced by the size of the regions and the length of labels. Turning `labels = off` might work if you plot a smaller region. We'll have to see how to tackle that. 

> the possibility to plot the normalized count of the matrices (not only log transformed data).
> the possibility to auto-width the matrices in order to have square bins (not diamond).

could you explain this two? is this for pyGenomeTracks or hicplotMatrix ?

**Comment by lldelisle** [comment]
Sorry, what I meant was:
1) Is it possible to plot the annotations without the labels?
2) Is it possible to force to plot the annotations on one row (even if the label overlap).
The rest is, I think, still for hicplotMatrix. I will put it back.

**Comment by lldelisle** [comment]
Sorry, it looks like everything is solved.

**Comment by vivekbhr** [comment]
Currently it's possible to plot only one row out of multiple from the gene annotation. I guess what you are looking for is the "collapsed" view of IGV (like the one attached)?
<img width="804" alt="screen shot 2018-12-14 at 10 03 36 pm" src="https://user-images.githubusercontent.com/8420267/50027336-28ff8800-ffec-11e8-8d5c-688f0889ce6c.png">

**Comment by lldelisle** [comment]
My problem with this IGV view is that some genes are missing:
![image](https://user-images.githubusercontent.com/30404086/50078095-5dd72f00-01e6-11e9-9751-d1eef0acfa70.png)
![image](https://user-images.githubusercontent.com/30404086/50078153-80694800-01e6-11e9-983e-c50057cfb226.png)
But maybe it is too complicated and not readable.

**Comment by bgruening** [comment]
@lldelisle  let us know if this does not work for you ;) lol. 
You can try the newest version here: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/

**Comment by lldelisle** [comment]
<img width="100" src="http://icons.iconarchive.com/icons/google/noto-emoji-smileys/1024/10003-face-with-tears-of-joy-icon.png">
