### ISSUE TITLE
ValueError: Format when using --BED

### ISSUE THREAD

**Issue by DoaneAS** [deeptools/pyGenomeTracks#52]
Hi, when using the --BED option to supply multiple regions to plot, I get an error about not specifying a filetype for output, because the --outFileName is prepended to the coordinates, e.g. `ValueError: Format "pdf_chr1:8938478-9238478" is not supported.`

Is there a hidden option to specify output file type?  

thanks

**Comment by vivekbhr** [comment]
Thanks for reporting. You're right the region name is appended to file name and this throws an error. if you don't specify the ending (.pdf) to output prefix, pygenometracks will produce png as default. I'll fix this issue and let you know..
