### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by daquang** [deeptools/pyGenomeTracks#54]
I would like to install pyGenomeTracks using pip, since there isn't yet a conda package available for MacOS Mojave running Anaconda with python 3.7. However, I get the following error after doing pip install:

    /var/folders/37/kbrfsr294cl4wq86whp5vn4h0000gn/T/H5closew0bllnx0.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]
        H5close();
        ^
    2 warnings generated.
    ld: library not found for -lhdf5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    * Using Python 3.7.0 (default, Jun 28 2018, 07:39:16)
    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.

**Comment by vivekbhr** [comment]
Could you place the installation command here? 
You can also try downloading our [environment.yml file](https://github.com/deeptools/pyGenomeTracks/blob/master/environment.yml) and install using your conda with the command `conda env create -f environment.yml`

**Comment by LeilyR** [comment]
This might help: `pip install h5py`
