### ISSUE TITLE
`file_type = domains` has to be set when plotting triangles (version 2.0)

### ISSUE THREAD

**Issue by GinaRe** [deeptools/pyGenomeTracks#55]
`file_type = domains` has to be set when plotting triangles (version 2.0) showing TADs. This is missing in the documentation. Using the example from the documentation does not work.

**Comment by fidelram** [comment]
Can you do a PR trying to fix this? That would be really helpful.

**Comment by lldelisle** [comment]
Hi,
With #149, we can now use `display = triangles` or `file_type = domains`. They would both give the same result. Thank you for spotting it.
