### ISSUE TITLE
KeyError: 'I'

### ISSUE THREAD

**Issue by sarah872** [deeptools/pyGenomeTracks#60]
I have two bed files, one generated from a `bam` and the other one generated from a `gff`.
They have a structure like this:

```
head gff.bed
chrI 	 0 	 62 	 TEL01L_telomeric_repeat 	60	 -
chrI 	 0 	 801 	 TEL01L 	60	 -
chrI 	 0 	 230218 	 chrI 	60	 .
chrI 	 62 	 336 	 TEL01L_X_element_combinatorial_repeat 	60	 -

head bam.bed
chrI	0	1574	9e439cde-c337-4cd6-adf2-beda246c108c	60	+
chrI	0	1513	31ae2db4-29b1-46fb-8d7f-94529b54af00	60	-
chrI	11179	26816	3e486d74-3165-4c5c-840c-ed4611925077	60	+
chrI	12468	22428	b29fae08-e8de-4401-80be-6838516bc907	60	+
```

I would like to display the region `10,090-13,000` of `chrI`, but I am getting the following error when I try the command `pyGenomeTracks --tracks tracks.ini --region chrI:10,090-13,000 --outFileName nice_image.pdf`

```
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:4.751986980438232
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 12.0. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [x-axis]
/home/user/viehboeck/.conda/envs/pygenometracks/lib/python3.6/site-packages/matplotlib/cbook/__init__.py:424: MatplotlibDeprecationWarning: 
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warn_deprecated("2.2", "Passing one of 'on', 'true', 'off', 'false' as a "
INFO:pygenometracks.tracksClass:plotting 2. [spacer]
INFO:pygenometracks.tracksClass:plotting 3. [gff_cut_real]
Traceback (most recent call last):
  File "/home/user/viehboeck/.conda/envs/pygenometracks/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/home/user/viehboeck/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/plotTracks.py", line 304, in main
    trp.plot(args.outFileName, *region, title=args.title)
  File "/home/user/viehboeck/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 246, in plot
    track.plot(plot_axis, chrom, start, end)
  File "/home/user/viehboeck/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/tracks/BedTrack.py", line 247, in plot
    genes_overlap = sorted(self.interval_tree[chrom_region][start_region:end_region])
KeyError: 'I'
```

**Comment by LeilyR** [comment]
An update to my answer from yesterday, I cannot produce that error. I even tested on the few lines of bed files you have sent, it seems fine on my side.

**Comment by sarah872** [comment]
I've tried the exmples that are provided and they run without an error.
I've attached the files that I am working with (yeast data), maybe you can have a look!

[bam+gff.zip](https://github.com/deeptools/pyGenomeTracks/files/2840569/bam%2Bgff.zip)

**Comment by LeilyR** [comment]
Good that you have sent me the files, I could easily see what the issue is. Your `gff.bed` file is not a correctly formatted bed file. Fix that first. For example you have a line like: 
`chrI 	 0 	 230218 	 chrI 	60	 . `

**Comment by sarah872** [comment]
Sorry, seems that I am blind. What exactly is the error in this line? It has 6 fields (chr name, start, stop, feature name, MAPQ, strand).

**Comment by LeilyR** [comment]
My apologies, I thought I have marked the issue. So the error is not that you don't 6 columns but its that the separation between columns are a mixture of tabs and spaces. So, you basically need to have something like this: (this is what I meant to send last time)
`chrI\t0\t230218\tchrI\t60\t.`
I have tested it on a subset of your regions and it worked. Please let me know if there was any issue left.

**Comment by sarah872** [comment]
Thanks a lot for the clarification!
