### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by iamjli** [deeptools/pyGenomeTracks#61]
https://github.com/deeptools/pyGenomeTracks/blob/2b434211b484c25fa7d21dd3dd821c67a4da30d3/pygenometracks/tracks/HiCMatrixTrack.py#L54

I believe this should be 

```
if "region" in self.properties: 
```

**Comment by fidelram** [comment]
did you get an error? I think that self.properties['region'] is initialized
previously.

**Comment by LeilyR** [comment]
properties['region'] is set after reading --region from the command line

**Comment by lldelisle** [comment]
Hi,
I am sorry but we could not reproduce the error. 
I will close the issue. 
Feel free to reopen it if you still need help.
