### ISSUE TITLE
Intervaltree API update breaking Epilogos track

### ISSUE THREAD

**Issue by dborgesr** [deeptools/pyGenomeTracks#65]
Hello,

So currently when i'm trying to visualize w/ the following epilogos_test.ini track file:

[Segway Chromatin State]
file = epilog.qcat.bgz

using the following command:
`
pyGenomeTracks --tracks epilogos_test.ini     --region chr19:39107638-39140062 --outFileName test_epilogos.png
`
I get this error:
`
AttributeError: 'EpilogosTrack' object has no attribute 'interval_tree'
`

I think this has to do w/ intervaltree getting updated to version 3.0.0 and it breaking the API. What's weird though is that i tried pinning version 2.1.0 of intervaltree and it still not working. 
Regardless, I think its something that might need a proper fix / may break other things.

**Comment by LeilyR** [comment]
Hi Diego,
I cannot produce this error. I wonder if there is something wrong with your `.ini` file. Maybe you could check our test data and the provided `.ini` file. You can also send me your `.ini` file if you want and I will have a look at it.

**Comment by dborgesr** [comment]
Gladly, so the .ini file i'm using is the following two lines :

[Segway Chromatin State]
file = epilog.qcat.bgz


I reduced it to JUST the example .qcat.bgz file. 

when i run:
pyGenomeTracks --tracks epilogos_test.ini --region chr19:39107638-39140062 --outFileName test_epilogos.png

I get the error i posted above.

I'm pretty sure its related to this issue (after doing some googling):
https://github.com/Gallopsled/pwntools/issues/1238

I'm doing this all inside a Docker container (which i can send to you) so the libraries etc are getting updated very quickly.

Thanks for the quick reply as well! I've been giving this error quite a bit of time with no luck :(

**Comment by LeilyR** [comment]
Hi Diego, 
I have generated a `.ini` file the exact same way as you did, also tested with interval tree v3 and I couldn't reproduce the error you have reported. Things you could check in my mind are 1. being sure about your `.bgz` file, maybe you can try the `qcat.bgz` test file from `pygenometracks/tests/test_data` and see if it works with that or even send me your file then I will test it here, 2. working on a fresh conda env, 3. check for python2 vs python3 , other than these I really cannot see how you get that error.

**Comment by dborgesr** [comment]
Very weird. Right, i'm using that qcat.bgz file when i'm testing (to make sure it wasn't my own), and i'm getting that error.

It sounds like something wonky is going w/ the conda environment, i'll give it some hack time and see what i can come up with.

**Comment by dborgesr** [comment]
Welp, after much trial and error I think the problem was two fold.

1. The gzipped bed needs to be indexed by tabix (I think i missed that somewhere)
2. It'll error out if it doesn't find the chromosome you're trying to show in the chromatin state track.

Now its working great! thanks for taking a look though and sorry for the runaround.
