### ISSUE TITLE
No entries in a chromosome causes an error

### ISSUE THREAD

**Issue by Phlya** [deeptools/pyGenomeTracks#67]
I have a bed file which has intervals only on certain chromosomes, and if I include it when creating figures for regions on other chromosomes, I get an error:
```
/usr/local/lib/python3.5/dist-packages/pygenometracks/tracks/BedTrack.py in plot(self, ax, chrom_region, start_region, end_region)
    245         chrom_region = self.check_chrom_str_bytes(self.interval_tree, chrom_region)
    246 
--> 247         genes_overlap = sorted(self.interval_tree[chrom_region][start_region:end_region])
    248 
    249         # turn labels off when too many intervals are visible.

KeyError: '11'

/usr/local/lib/python3.5/dist-packages/matplotlib/colors.py:1028: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0
```
I think a simple fix would be to use `self.interval_tree.get(chrom_region, [])[start_region:end_region]` instead of `self.interval_tree[chrom_region][start_region:end_region]` on line 247 - assuming expected output is just an empty list.

**Comment by LeilyR** [comment]
Thanks Phyla! I have tried calling pygenomeTrack on a region which is not inside any of the files that are addressed in tracks.ini and could produce the error. I will working on that and will let you know when it is done.

**Comment by LeilyR** [comment]
Hi Phyla! I fixed this by adding an error message for the user if the provided chromosome names cannot be found in the input files. The program doesn't crash though but keeps looking for the next regions in the bed file. At the end, tracks which don't share a chromosome name with the asked regions will be empty in the output figure. This can be found in dev. branch now and soon will be merged to the master branch. Hope this solves you issue.

**Comment by Phlya** [comment]
Thank you! I will try it when I have a minute.
