### ISSUE TITLE
Hi-C matrix format

### ISSUE THREAD

**Issue by crazyhottommy** [deeptools/pyGenomeTracks#7]
I noticed that a `.h` format is used. I have the raw bin files, how should I change it to the format pyGenomeTracks require?

```
Bin1	Bin2	Bin3	Bin4	Bin5	Bin6
7.85957	4.80329	11.4766	9.57416	4.5288	8.55022
8.61621	4.98956	2.35654	5.69483	11.1187	10.1322
4.06803	4.07801	7.98047	2.59144	6.3851	7.74306
4.52869	2.70624	8.94544	4.29185	8.29491	8.38257
2.91472	3.84658	1.56752	4.48515	7.4955	8.77461
3.08096	2.96487	7.23623	2.33142	3.08529	5.5379
3.12141	3.06905	4.97247	2.39298	5.03621	7.22344
3.4037	2.26455	1.48176	1.41958	3.40252	7.7027
3.8696	1.41425	7.68872	2.21027	5.06846	3.20063

```

Thanks,
Tommy

**Comment by fidelram** [comment]
take a look at http://hicexplorer.readthedocs.io/en/documentation/content/tools/hicExport.html

That will take a matrix in different formats and export them as a hicexplorer format (.h5)

I think the ren format may be the one you need. The documentation has some explanation of the format (in the readthedocs page you will need to scroll to horizontally to read the full explanation).

**Comment by crazyhottommy** [comment]
Thank you very much for the link!
