### ISSUE TITLE
[install] hicexplorer breaks python2 install

### ISSUE THREAD

**Issue by shouldsee** [deeptools/pyGenomeTracks#70]
Was trying to `pip2` in a docker. `hicexplorer` broke the call
```
Collecting hic2cool>=0.4 (from hicexplorer>=2.1.1->pyGenomeTracks->-r requirements.txt (line 37))
  Downloading https://files.pythonhosted.org/packages/8d/6d/a75f15ea12c70bc12ee168a16d2ad347baa326465
3365902ebe6018661a1/hic2cool-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d3w6Uh/hic2cool/setup.py", line 52, in <module>

```

**Comment by joachimwolff** [comment]
Hi,

we do not support Python 2 anymore. Please update to current Python 3, we will not give any support for outdated versions.

Best,

Joachim

**Comment by shouldsee** [comment]
This is disappointing.

**Comment by dpryan79** [comment]
@shouldsee You'll notice that this is increasingly the case, since major dependencies have dropped python 2 support and python 2 itself will [reach end of life soon](https://pythonclock.org/).

**Comment by shouldsee** [comment]
@dpryan79 . Yeah but I just love the `print` keyword in python2.
