### ISSUE TITLE
What is the best way to prepare genes.bed.gz from gencode?

### ISSUE THREAD

**Issue by yyoshiaki** [deeptools/pyGenomeTracks#72]
Hi,
I'm trying to show GENCODE as a gene track. I tried several patterns but I couldn't get what I expected. In concrete, I prepared bed12 using the script [here](https://davetang.org/muse/2012/09/12/gencode/) and sorted and converted gene ids into symbols. 

From the results (showing below), I may be able to use the flybase style, but somehow the UCSC style ends up in the weird strand directions.

Now, I want to know the best way to show an appropriate gene track. How should I prepare the bed12 from gtf or do you have a plan to add gtf as an applicable file format?

Best,
Yoshi

![image](https://user-images.githubusercontent.com/19543497/57116052-a6564a00-6d8d-11e9-9bf0-1bac034ba4d8.png)

**Comment by yyoshiaki** [comment]
Thank you Leily.
So far, we succeeded to convert gtf to bed12 using gtfToGenePred and Genepredtobed as;

```
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_30/gencode.v30.basic.annotation.gtf.gz
gtfToGenePred gencode.v30.basic.annotation.gtf.gz gencode.v30.basic.annotation.gp -geneNameAsName2 -ignoreGroupsWithoutExons -genePredExt
awk '{ print $12"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9"\t"$10"\t"$11"\t"$12"\t"$13"\t"$14"\t"$15"\t"}' gencode.v30.basic.annotation.gp > gencode.v30.basic.annotation.gene_name.gp
genePredToBed gencode.v30.basic.annotation.gene_name.gp gencode.v30.basic.annotation.bed12
bedtools sort -i gencode.v30.basic.annotation.bed12 > gencode.v30.basic.annotation.sort.bed12
```

but this is too bothersome. 
I'm looking forward to seeing the new feature soon.

**Comment by lldelisle** [comment]
You can now use gtf files if you use file_type = bed.

**Comment by bgruening** [comment]
@yyoshiaki let us know if this does not work for you. Thanks.
You can try the newest version here: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/
