### ISSUE TITLE
Single Exon Transcript UCSC version

### ISSUE THREAD

**Issue by ledwmp** [deeptools/pyGenomeTracks#77]
pyGenomeTracks 2.1
python2.7.12

pyGenomeTracks --tracks tracks_new.ini --region chrZ:1-13581 --outFileName blahblah.svg

title not set for 'section 8. [blahblah]'
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:0.0181858539581
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 18.3. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [x-axis]
/home/mitch/.local/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
INFO:pygenometracks.tracksClass:plotting 2. [spacer]
INFO:pygenometracks.tracksClass:plotting 3. [blah1]
INFO:pygenometracks.tracksClass:plotting 4. [blah2]
INFO:pygenometracks.tracksClass:plotting 5. [blah3]
INFO:pygenometracks.tracksClass:plotting 6. [blah4]
INFO:pygenometracks.tracksClass:plotting 7. [spacer]
INFO:pygenometracks.tracksClass:plotting 8. [bedfile1]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 790.0,0
INFO:pygenometracks.tracksClass:plotting 9. [spacer]
INFO:pygenometracks.tracksClass:plotting 10. [bedfile2]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 100,0

bedfile1 example:
chrZ	2341	4681	gene1	.	+	2365	4638	.	1	2340	0

relevant tracks_new.ini section:
[bedfile1]
file=bedfile1.bed

# title of track (plotted on the right side)
# height of track in cm (ignored if the track is overlay on top the previous track)
height = 3
# if the track wants to be plotted upside-down:
# orientation = inverted
# if the track wants to be plotted on top of the previous track. Options are 'yes' or 'share-y'. For the 'share-y'
# option the y axis values is shared between this plot and the overlay plot. Otherwise, each plot use its own scale
#overlay previous = yes

# if the type=genes is given
# the the file is interpreted as gene
# file. If the bed file contains the exon
# structure (bed 12) then this is plotted. Otherwise
# a region **with direction** is plotted.
# if the bed file contains a column for color (column 9), then this color can be used by
# setting:
# color = bed_rgb
color = darkblue
#if color is a valid colormap name (like RbBlGn), then the score is mapped
# to the colormap. If the color is simply a color name, then this color is used and the score is not considered.
# For the colormap option, the the min_value and max_value for the score can be provided, otherwise
# the maximum score and minimum score found are used.
#color = RdYlBu
#min_value=0
#max_value=100
# height of track in cm
height = 3
# to turn off/on printing of labels
labels = off
# optional: font size can be given to override the default size
fontsize = 5
# optional: line width
#line width = 2.5
# the display parameter defines how the bed file is plotted.
# The options are ['colapsed', 'interleaved', 'triangles'] This options asume that the regions do not overlap.
# `collapsed`: The bed regions are plotted one after the other in one line.
# `interleaved`: The bed regions are plotted in two lines, first up, then down, then up etc.
# if display is not given, then each region is plotted using the gene style
#optional, default is black. To remove the background color, simply set 'color' and 'background color' to the
# same value
#border color = black
# style to plot the genes when they have exon information
display = interleaved
style = UCSC
#style = flybase
# maximum number of gene rows to be plotted. This
# field is useful to limit large number of close genes
# to be printed over many rows. When several images want
# to be combined this must be set to get equal size, otherwise, on each image the height of each gene changes
#gene rows = 1
# if the track wants to be plotted on top of the previous track. Options are 'yes' or 'share-y'. For the 'share-y'
# option the y axis values is shared between this plot and the overlay plot. Otherwise, each plot use its own scale
#overlay previous = yes
# by default the ymax is the number of
# rows occupied by the genes in the region plotted. However,
# by setting this option, the global maximum is used instead.
# This is useful to combine images that are all consistent and
# have the same number of rows.
#global max row = yes
# optional. If not given is guessed from the file ending.
file_type = bed

Does pyGenomeTracks 2.1 allow visualization of single-exon UCSC-style bed files? With output above and example bed file, the thickstart is functional, but the program appears to ignore the thickend column. I can otherwise plot multi-exon bed files.

**Comment by ledwmp** [comment]
"Fixed" by including artificial intron of length 0 in bed12:
chrZ	2341	4681	gene1	.	+	2365	4638	.	2	50,2290	0,50

**Comment by vivekbhr** [comment]
sounds good. 👍
