### ISSUE TITLE
Can you provide the docker version of the runtime environment?

### ISSUE THREAD

**Issue by guojinpeng** [deeptools/pyGenomeTracks#78]

**Comment by vivekbhr** [comment]
docker is available through [bioconda](http://bioconda.github.io/recipes/pygenometracks/README.html). Did you try `docker pull quay.io/biocontainers/pygenometracks:<tag>` ?

**Comment by lldelisle** [comment]
I close the issue but if you still need it, do not hesitate to reopen it.
