### ISSUE TITLE
Missing y-axis scale on hicPlotTADs

### ISSUE THREAD

**Issue by StephenRicher** [deeptools/pyGenomeTracks#79]
Hi,

I am making great use of this tool but am having trouble with plotting a scale bar on the HiC matrix generated via hicPlotTADs.

My figure looks the same as one of your test images at: https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/test/test_data/hicPlotTADs/pygenometracks.png 

The colour scale bar is present but no numbers are there. I can't find the .ini file associated with the above test data plot but I was wondering if there was a setting in the configuration file that is causing these to not be plotted? As in the above figure all my other tracks plot the scales correctly.

Thanks,
Stephen

**Comment by vivekbhr** [comment]
@StephenRicher are you able to reproduce this issue with pyGenomeTracks? If yes. please let us know the version number, config file and an example output.

**Comment by StephenRicher** [comment]
Hi,

Yep I have the same issue - I've attached a basic config file and test output below. I am using pyGenomeTracks 3.0. 

Thanks,
Stephen

![test](https://user-images.githubusercontent.com/45041598/59927957-8e1db580-9435-11e9-8630-ccc69db39863.png)

[tracks.txt](https://github.com/deeptools/pyGenomeTracks/files/3314761/tracks.txt)

**Comment by vivekbhr** [comment]
Yes this looks like a known issue. The labels were missing for ticks when you use log1p with certain matplotlib versions. I think updating your matplotlib would help

**Comment by kimj50** [comment]
hi, I also ran into a similar problem. hicexplorer or pygenometrack doesn't show the tickmarks.
I am currently using: pygenometracks v3.0, matplotlib v3.0.3. 
track:
[x-axis]
where = top

[hic matrix]
file = /scratch/kimj50/elegans/matrix_normalize/N2_2017_emb_sum_5kb_correct_normalize.h5
title = test
depth = 1000000
transform = log

[test.pdf](https://github.com/deeptools/pyGenomeTracks/files/3378522/test.pdf)

**Comment by lldelisle** [comment]
Hi, I also have the same issue with pyGenomeTracks 3.0 with matplotlib v3.1.1 but also v3.0.3, and v3.0.1...

**Comment by lldelisle** [comment]
This is now solved since v3.1.
