### ISSUE TITLE
Problem with colorbar

### ISSUE THREAD

**Issue by tkzeng** [deeptools/pyGenomeTracks#80]
Some weird lines appear to the left of the plot; they seem to be from a colorbar. Is there something wrong with any of my commands / config files? I would like to either remove the lines, or if they are from a colorbar, to get it to display correctly. I have attached the ini file as well (renamed to a txt so it attaches). Thanks!

![image](https://user-images.githubusercontent.com/21118492/60465042-c2ebf280-9c15-11e9-88eb-76a7b79e38bd.png)

[chr10-1058405-1058516.ini.txt](https://github.com/deeptools/pyGenomeTracks/files/3347257/chr10-1058405-1058516.ini.txt)

**Software versions:**
pyGenomeTracks 3.0
Python 3.6.7

**Output:**
```
title not set for 'section 6. [10-1034895-0]'

title not set for 'section 8. [bigwig]'

title not set for 'section 10. [bigwig]'

title not set for 'section 12. [bigwig]'
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:5.124847412109375
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 6.0. Dpi is set to 220

INFO:pygenometracks.tracksClass:plotting 1. [x-axis]
/project2/yangili1/tonyzeng/software/miniconda3/envs/test/lib/python3.6/site-packages/matplotlib/cbook/__init__.py:424: MatplotlibDeprecationWarning:
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warn_deprecated("2.2", "Passing one of 'on', 'true', 'off', 'false' as a "
INFO:pygenometracks.tracksClass:plotting 2. [spacer]
INFO:pygenometracks.tracksClass:plotting 3. [refseq.sorted]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 229.99999999999997,0
INFO:pygenometracks.tracksClass:plotting 5. [spacer]
INFO:pygenometracks.tracksClass:plotting 6. [10-1034895-0]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 100,0
INFO:pygenometracks.tracksClass:plotting 8. [bigwig]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 100,0
INFO:pygenometracks.tracksClass:plotting 10. [bigwig]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 100,0
INFO:pygenometracks.tracksClass:plotting 12. [bigwig]
```

**Command:**
`pyGenomeTracks --tracks chr10-1058405-1058516.ini --region chr10:1052818-1063742 --outFileName chr10-1058405-1058516.png --dpi 220
`

**Comment by vivekbhr** [comment]
Could you try removing the lines `color = #003cd6[10-1034895-1]` and `color = #003cd6[10-1034895-2]` from the ini and try again?

**Comment by tkzeng** [comment]
I've figured out the problem--it is because the height is too small. Using height = 1 fixed the problem. (Thanks for pointing out the weird lines, they should be separated by a line break; I don't think they caused any problems though.)
