### ISSUE TITLE
Incompatibility with python3.7 in conda

### ISSUE THREAD

**Issue by lldelisle** [deeptools/pyGenomeTracks#86]
Hi,
Just to tell you that for the moment, h5py has issues with python 3.7. As pyGenomeTracks depends on hicmatrix which depends on h5py, for the moment it is not working.
I already reported the issue to [h5py,](https://github.com/h5py/h5py/issues/1172) let's hope they solve it.
The problem is that when you install pyGenomeTracks through conda:
`conda create --name justpygenometrack pygenometracks`
it uses python3.7 and thus it fails.
People would need to do:
`conda create --name justpygenometrack pygenometracks python=3.6`
This issue is not happening with hicexplorer because 
hicexplorer[version='>=2.1.1'] -> fit_nbinom[version='>=1.1'] -> python[version='<3.7']
This is also why it does not fail if you use the environment provided in the github. It is because you put `hicexplorer >= 2.1.1` whereas in the conda recipe you put `hicmatrix >=9`.

Lucille

**Comment by dpryan79** [comment]
Ugh, it sucks that that h5py issue hasn't been resolved :( Thanks for the heads up though.

**Comment by lldelisle** [comment]
Apparently, from what I understood the problem is the conda package h5py for python 3.7 which has been built with hdf5 1.10.4 instead of hdf5 1.10.5. Because I have locally python 3.7 with h5py and it works perfectly fine.

**Comment by bgruening** [comment]
Trying to resolve this at https://github.com/conda-forge/h5py-feedstock/pull/58

**Comment by lldelisle** [comment]
This is solved.
