### ISSUE TITLE
In Hi-C tracks, is boundaries_file used?

### ISSUE THREAD

**Issue by lldelisle** [deeptools/pyGenomeTracks#87]
Hi,
In the galaxy tool, there is a properties which is boundaries_file, however, I do not see it used. Was it used in a very old version and has been replaced now by TADsTrack with an overlay?
Many thanks,

Lucille

**Comment by bgruening** [comment]
I think that was use to plot boundaries over a HiC track: https://github.com/deeptools/HiCBrowser/blob/6c8fe0b20e5ba64904db31ccff3127aa94d0907c/region_tracks.ini#L30

I think it can still be used: https://github.com/deeptools/pyGenomeTracks/commit/8a7c696486d764bcc583546fbf838379538c7cf8

**Comment by lldelisle** [comment]
No it is not used anymore, if specified, parse_tracks will check it is a file which exists but then it is not used in the HiCMatrixTrack class... Maybe it was when it was in hicexplorer... I do not know if we should put a warning...
