### ISSUE TITLE
Alpha property in BigWig overlay is not working

### ISSUE THREAD

**Issue by mnmldani** [deeptools/pyGenomeTracks#96]
I am using pyGenomeTracks to generate figures of different bigwig tracks and bedfiles, also involving overlays of tracks.
I precisely followed the examples for this but somehow the transparency option does not work and I cannot figure out why. 
I even considered the possibility that my matplotlib version has a bug but when using the `ax.fill_between` function with the same arguments the result came out transparent.

My tracks.ini file looks as follows:
```
[x-axis]
where = top

[bigwig]
file = track1.bw
title = track1
height = 4
color = cornflowerblue
alpha = 0.5
type = fill

[bigwig]
file = track2.bw
title = track2
height = 4
color = lightcoral
alpha = 0.5
type = fill
overlay previous = share-y
```

the command used is:
`pyGenomeTracks --tracks resource/alphatest.ini --region chr15:61,815,640-61,823,171 -o tansparent_overlay.pdf`

where the regions specified apply to the mouse mm9 genome assembly and the software runs smoothly giving:
```
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:0.020897626876831055
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 5.5. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [x-axis]
INFO:pygenometracks.tracksClass:plotting 2. [bigwig]
INFO:pygenometracks.tracksClass:plotting 3. [bigwig]
```
as output, indicating no problems with the initiation file.

I use python version 3.7.3 with pyGenomeTracks version 3.0 matplotlib version 3.1.0

Do you have a clue, whats going on?

**Comment by bgruening** [comment]
@mnmldani can you please try the latest version of pyGenomeTracks (3.1.1), there are a few fixes included.

**Comment by mnmldani** [comment]
Works fine now. Thanks
