### ISSUE TITLE
manual for all the supported settings?

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/pyGenomeTracks#97]
Hi, this is an amazing plotting tool! I have been using it a lot, but one thing I wasn't able to find is a manual or a site that describes all the possible settings that can be customized, besides the one  README file (height, fontsize, color, etc). For instance, I  wasn't sure if changing the background color of each track is supported. Could anyone please let me know if there is a way to find this out?
Thank you!

**Comment by bgruening** [comment]
@rikrdo89 thanks for this issue. Documentation is really missing at the moment. What we have is a few examples in https://github.com/deeptools/pyGenomeTracks/tree/master/examples and a graphical user-interface with a most, if not all, options: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/

I hope that helps you a little bit. We hope to create some documentation later this year.
Sorry!

**Comment by rikrdo89** [comment]
thank you, this is helpful. I have another question about a warning I keep getting related to the maximun number of threads... I will open a new issue.

**Comment by lldelisle** [comment]
Hi,
For the moment, the background color is not something we can set but I could add it to my TODO list, as well as the documentation, for sure.
What can help you to know all the options is to use make_tracks_file 
```
usage: make_tracks_file --trackFiles <bigwig file> <bed file> etc. -o tracks.ini

Facilitates the creation of a configuration file for pyGenomeTracks. The
program takes a list of files and does the boilerplate for the configuration
file.

optional arguments:
  -h, --help            show this help message and exit
  --trackFiles TRACKFILES [TRACKFILES ...], -f TRACKFILES [TRACKFILES ...]
                        Files to use in for the tracks. The ending of the file
                        is used to define the type of track. E.g. `.bw` for
                        bigwig, `.bed` for bed etc. For a arcs or links file,
                        the file ending recognized is `.arcs` or `.links`
                        (default: None)
  --out output file, -o output file
                        File to save the tracks (default: None)
  --version             show program's version number and exit
```

**Comment by lldelisle** [comment]
Hi,
For the moment, a full documentation is still missing but since #149 all available settings are available in the README, in the new section: https://github.com/deeptools/pyGenomeTracks#possible-parameters. In addition, the output of `make_tracks_file` has been updated to describe all possible parameters.
I still hope to do a more descriptive documentation.

**Comment by lldelisle** [comment]
Hi,
pygenometracks is now available in [readsthedocs](https://pygenometracks.readthedocs.io):
![image](https://user-images.githubusercontent.com/30404086/77414747-cc2f7780-6dc1-11ea-93ea-52dbbf7a70bd.png)
