### ISSUE TITLE
numbers of cores / threads detected

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/pyGenomeTracks#98]
Whenever I run the following command, I get the following warning.

$ pyGenomeTracks --tracks tracks.ini --region chr3:34,500,000-35,000,000 --outFileName plot.png

INFO:numexpr.utils:Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

I am able to get the plots, but I would like to know i there is any way to set the number of threads or cores so i don't keep getting this warning. Thanks for your help.

**Comment by bgruening** [comment]
That is nothing we can control. It is a info message from one of our dependencies. You can use tricks like this here: https://stackoverflow.com/questions/23692950/how-do-you-suppress-output-in-ipython-notebook

Or if you use the commandline you can also redirect the output to `> /dev/null`

**Comment by joachimwolff** [comment]
Get this in HiCExplorer too, as an intermediate solution to not confuse users I simply muted it:

Add to `__init__.py`
```
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger('numexpr').setLevel(logging.WARNING)
```

**Comment by joachimwolff** [comment]
See PR #100.

**Comment by MzwaneleN** [comment]
Hi. How would I circumvent the issue in a HPC environment? My HiCExplorer job gives out the same error as above and after some time it gets "killed". Thanks

**Comment by lldelisle** [comment]
Could you open a new issue please with the version you are using the way you installed it (conda or pip), if possible the INI file and the whole output you get.
In this issue there was a message but no error.
Thanks

**Comment by Torcelllo** [comment]
Set an Environment Variable NUMEXPR_MAX_THREADS to whatever your GPU can support
